In [1]:
%pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl (27.6 MB)
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   --- ------------------------------------ 2.4/27.6 MB 19.2 MB/s eta 0:00:02
   ---------------- ----------------------- 11.3/27.6 MB 35.2 MB/s eta 0:00:01
   ----------------------------- ---------- 20.7/27.6 MB 39.6 MB/s eta 0:00:01
   ---------------------------------------- 27.6/27.6 MB 38.1 MB/s eta 0:00:00
Installing collected packages: pyarrow
Successfully installed pyarrow-23.0.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
from pathlib import Path
import pandas as pd
import re

**Data exploration**

In [3]:
REPO_ROOT = Path(".").resolve().parent
DATA_PATH = REPO_ROOT / "data"
MODEL_PATH = REPO_ROOT / "models"
OUTPUT_PATH = REPO_ROOT / "output"
INDEX_PATH = REPO_ROOT / "data" / "processed"

LAWS_CSV = DATA_PATH / "laws_de.csv"
COURTS_CSV = DATA_PATH / "court_considerations.csv"
TRAIN_CSV = DATA_PATH / "train.csv"
TEST_CSV = DATA_PATH / "test.csv"
VAL_CSV = DATA_PATH / "val.csv"

In [4]:
train_data = pd.read_csv(TRAIN_CSV)

train_data.head(5)

,query_id,query,gold_citations
0,train_0001,Die A AG betreibt seit den 1970er-Jahren auf d...,Art. 10a Abs. 1 USG;Art. 2 Abs. 1 UVPV;Art. 10...
1,train_0002,Die Alpha Consulting AG kann nun ihr Grundstüc...,Art. 975 ZGB;Art. 974 Abs. 2 ZGB;Art. 973 ZGB;...
2,train_0003,Das Kompetenzzentrum Völkerstrafrecht bei der ...,Art. 264m StGB
3,train_0004,Die Linzer Stadtbahn AG ('LiSA') ist die priva...,Art. 176 Abs. 1 IPRG;Art. 186 Abs. 1 IPRG;Art....
4,train_0005,Die Stadt Winterthur beschloss am 10. Februar ...,Art. 93 Abs. 1 BGG;Art. 89 Abs. 1 BGG;Art. 89 ...

In [5]:
laws_data = pd.read_csv(LAWS_CSV)   

laws_data.head(5)

,citation,text,title
0,Art. 1 112,Die Einwohnergemeinde Bern tritt der Schweizer...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
1,Art. 2 112,Die Einwohnergemeinde Bern wird ferner der Sch...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
2,Art. 3 Abs. 1 112,1 Falls die Schweizerische Eidgenossenschaft z...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
3,Art. 3 Abs. 2 112,2 Durch Anlage des neuen Verwaltungsgebäudes a...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
4,Art. 4 Abs. 1 112,1 Die Einwohnergemeinde Bern übernimmt im fern...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...

In [6]:
court_csv = pd.read_csv(COURTS_CSV)   

court_csv.head(5)

                   citation                                               text
0  BGE 139 I 2 E. 1.12.2011  betr. Verweigerung der Beiladung seien gutzuhe...
1          BGE 139 I 2 E. 2  Eventualiter sei die Rückweisung an die Vorins...
2        BGE 139 I 2 E. 5.1  In der Sache ist vorweg zu prüfen, ob der Ents...
3        BGE 139 I 2 E. 5.2  Art. 34 Abs. 1 BV gewährleistet in allgemeiner...
4        BGE 139 I 2 E. 5.3  Im vorliegenden Fall geht es nicht um die Gült...

In [7]:
print(f"Total Rows: {len(train_data)}")
print(train_data.isnull().sum())

Total Rows: 1139
query_id          0
query             0
gold_citations    0
dtype: int64

In [8]:
train_data['query_len'] = train_data['query'].apply(len)
train_data['num_citations'] = train_data['gold_citations'].apply(lambda x: len(str(x).split(';')))

print(train_data[['query_len', 'num_citations']].describe())

          query_len  num_citations
count   1139.000000    1139.000000
mean    1620.304653       4.090430
std     3019.878360       4.512206
min       40.000000       1.000000
25%      441.000000       1.000000
50%     1016.000000       2.000000
75%     1795.000000       5.000000
max    32767.000000      44.000000

In [9]:
train_data.head(5)

,query_id,query,gold_citations,query_len,num_citations
0,train_0001,Die A AG betreibt seit den 1970er-Jahren auf d...,Art. 10a Abs. 1 USG;Art. 2 Abs. 1 UVPV;Art. 10...,1495,3
1,train_0002,Die Alpha Consulting AG kann nun ihr Grundstüc...,Art. 975 ZGB;Art. 974 Abs. 2 ZGB;Art. 973 ZGB;...,1376,11
2,train_0003,Das Kompetenzzentrum Völkerstrafrecht bei der ...,Art. 264m StGB,1095,1
3,train_0004,Die Linzer Stadtbahn AG ('LiSA') ist die priva...,Art. 176 Abs. 1 IPRG;Art. 186 Abs. 1 IPRG;Art....,2899,4
4,train_0005,Die Stadt Winterthur beschloss am 10. Februar ...,Art. 93 Abs. 1 BGG;Art. 89 Abs. 1 BGG;Art. 89 ...,5763,6

In [10]:
all_citations = train_data['gold_citations'].str.split(';').explode().str.strip()

citation_counts = all_citations.value_counts().reset_index()
citation_counts.describe()

             count
count  2695.000000
mean      1.728757
std       1.505338
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max      20.000000

In [11]:
list(all_citations)

['Art. 10a Abs. 1 USG',
 'Art. 2 Abs. 1 UVPV',
 'Art. 10a Abs. 1 UVG',
 'Art. 975 ZGB',
 'Art. 974 Abs. 2 ZGB',
 'Art. 973 ZGB',
 'Art. 661 ZGB',
 'Art. 956a ZGB',
 'Art. 956a Abs. 3 ZGB',
 'Art. 955 Abs. 1 ZGB',
 'Art. 976 ZGB',
 'Art. 976a ZGB',
 'Art. 60 OR',
 'Art. 955 Abs. 2 ZGB',
 'Art. 264m StGB',
 'Art. 176 Abs. 1 IPRG',
 'Art. 186 Abs. 1 IPRG',
 'Art. 186 Abs. 3 IPRG',
 'Art. 190 Abs. 3 IPRG',
 'Art. 93 Abs. 1 BGG',
 'Art. 89 Abs. 1 BGG',
 'Art. 89 Abs. 2 BGG',
 'Art. 50 BV',
 'Art. 95 BGG',
 'Art. 106 Abs. 2 BGG',
 'Art. 42 Abs. 1 StGB',
 'Art. 106 StGB',
 'Art. 42 Abs. 4 StGB',
 'Art. 626 Abs. 1 ZGB',
 'Art. 626 Abs. 2 ZGB',
 'Art. 630 ZGB',
 'Art. 69 DBG',
 'Art. 358 OR',
 'Art. 337 OR',
 'Art. 361 OR',
 'Art. 11 StGB',
 'Art. 29 StGB',
 'Art. 111 StGB',
 'Art. 158 StGB',
 'Art. 117 StGB',
 'Art. 102 Abs. 1 StGB',
 'Art. 102 Abs. 2 StGB',
 'Art. 102 StGB',
 'Art. 102 Abs. 4 StGB',
 'Art. 706 OR',
 'Art. 717 OR',
 'Art. 643 OR',
 'Art. 716a Abs. 1 OR',
 'Art. 12 Abs. 2 StGB',
 'Art. 65 StGB',
 'Art. 65 Abs. 1 StGB',
 'Art. 50 FINMAG',
 'Art. 156 FinfraG',
 'Art. 144 FinfraG',
 'Art. 8 DSG',
 'Art. 8 Abs. 5 DSG',
 'Art. 9 Abs. 1 DSG',
 'Art. 9 Abs. 4 DSG',
 'Art. 9 Abs. 5 DSG',
 'Art. 13 BV',
 'Art. 36 BV',
 'Art. 83 AIG',
 'Art. 44 AsylG',
 'Art. 83 Abs. 2 AIG',
 'Art. 83 Abs. 3 AIG',
 'Art. 25 Abs. 3 BV',
 'Art. 83 Abs. 4 AIG',
 'Art. 41 Abs. 2 AIG',
 'Art. 4 StromVV',
 'Art. 6 Abs. 3 StromVG',
 'Art. 4 Abs. 1 StromVV',
 'Art. 15 StromVG',
 'Art. 15 Abs. 1 StromVG',
 'Art. 15 Abs. 2 StromVG',
 'Art. 15 Abs. 3 StromVG',
 'Art. 49 Abs. 1 BV',
 'Art. 22 Abs. 2 StromVG',
 'Art. 58 Abs. 1 FIDLEG',
 'Art. 3 FIDLEG',
 'Art. 59 Abs. 1 FIDLEG',
 'Art. 86 Abs. 3 FIDLEV',
 'Art. 9 SebG',
 'Art. 32 VGG',
 'Art. 86 Abs. 1 BGG',
 'Art. 83 BGG',
 'Art. 86 Abs. 2 BGG',
 'Art. 32 Abs. 1 OR',
 'Art. 396 Abs. 1 OR',
 'Art. 33 Abs. 3 OR',
 'Art. 396 Abs. 3 OR',
 'Art. 3 AsylG',
 'Art. 49 AsylG',
 'Art. 53 AsylG',
 'Art. 54 AsylG',
 'Art. 55 AsylG',
 'Art. 7 Abs. 3 FINMAG',
 'Art. 26 ArGV 3',
 'Art. 15 Abs. 2 JStG',
 'Art. 19 Abs. 3 JStG',
 'Art. 426 Abs. 1 ZGB',
 'Art. 426 ZGB',
 'Art. 19 Abs. 2 JStG',
 'Art. 221 StPO',
 'Art. 20 Abs. 3 DBG',
 'Art. 20 Abs. 1 DBG',
 'Art. 2 Abs. 2 URG',
 'Art. 10 URG',
 'Art. 9 Abs. 2 URG',
 'Art. 19 Abs. 1 URG',
 'Art. 11 URG',
 'Art. 25 URG',
 'Art. 19 URG',
 'Art. 12 URG',
 'Art. 28 URG',
 'Art. 62 Abs. 1 URG',
 'Art. 28 ZGB',
 'Art. 3 DSG',
 'Art. 4 Abs. 1 DSG',
 'Art. 4 Abs. 2 DSG',
 'Art. 4 Abs. 4 DSG',
 'Art. 14 DSG',
 'Art. 4 Abs. 3 DSG',
 'Art. 5 DSG',
 'Art. 34 DSG',
 'Art. 62b RVOG',
 'Art. 16 Abs. 2 EleG',
 'Art. 62b Abs. 3 RVOG',
 'Art. 28 ZGB',
 'Art. 186 Abs. 1 IPRG',
 'Art. 186 Abs. 2 IPRG',
 'Art. 9 GwG',
 'Art. 11 StGB',
 'Art. 37 GwG',
 'Art. 8 ZGB',
 'Art. 51 Abs. 3 ZPO',
 'Art. 308 ZPO',
 'Art. 309 ZPO',
 'Art. 47 Abs. 1 ZPO',
 'Art. 40 PatG',
 'Art. 40a PatG',
 'Art. 90 SchKG',
 'Art. 91 Abs. 1 SchKG',
 'Art. 17 Abs. 1 SchKG',
 'Art. 17 Abs. 2 SchKG',
 'Art. 31 SchKG',
 'Art. 960e OR',
 'Art. 960a Abs. 4 OR',
 'Art. 8a SchKG',
 'Art. 271 SchKG',
 'Art. 271 Abs. 1 SchKG',
 'Art. 82 SchKG',
 'Art. 83 Abs. 1 SchKG',
 'Art. 82 Abs. 1 SchKG',
 'Art. 257 ZPO',
 'Art. 257 Abs. 1 ZPO',
 'Art. 243 Abs. 1 ZPO',
 'Art. 354 ZPO',
 'Art. 341 Abs. 1 OR',
 'Art. 337c OR',
 'Art. 722 OR',
 'Art. 75 ZGB',
 'Art. 641 Abs. 2 ZGB',
 'Art. 679 ZGB',
 'Art. 58 Abs. 1 SVG',
 'Art. 7 SVG',
 'Art. 71 Abs. 1 SVG',
 'Art. 58 Abs. 2 SVG',
 'Art. 49 OR',
 'Art. 24 Abs. 1 UVG',
 'Art. 74 Abs. 2 ATSG',
 'Art. 21 JStG',
 'Art. 11 Abs. 1 JStG',
 'Art. 21 Abs. 1 JStG',
 'Art. 56 Abs. 1 DBG',
 'Art. 58 Abs. 1 DBG',
 'Art. 959 Abs. 2 OR',
 'Art. 4 Abs. 1 VStG',
 'Art. 20 Abs. 1 VStV',
 'Art. 14 Abs. 1 VStG',
 'Art. 20 Abs. 1 VStG',
 'Art. 24 Abs. 1 VStV',
 'Art. 15 FIDLEG',
 'Art. 2 Abs. 1 FIDLEG',
 'Art. 3 FIDLEG',
 'Art. 973c OR',
 'Art. 973d OR',
 'Art. 2 Abs. 1 FinfraV',
 'Art. 3 FINIG',
 'Art. 19 FINIV',
 'Art. 2 HRegV',
 'Art. 6 BankV',
 'Art. 8 Abs. 1 FIDLEG',
 'Art. 8 Abs. 2 FIDLEG',
 'Art. 9 Abs. 1 FIDLEV',
 'Art. 8 Abs. 3 FIDLEG',
 'Art. 8 Abs. 4 FIDLEG',
 'Art. 58 FIDLEG',
 'Art. 2 Abs. 2 FIDLEV',
 'Art. 59 Abs. 1 FIDLEG',
 'Art. 8 Abs. 5 FIDLEG',
 'Art. 9 Abs. 1 FIDLEG',
 'Art. 10 FIDLEG',
 'Art. 11 FIDLEG',
 'Art. 12 FIDLEG',
 'Art. 5 Abs. 1 FIDLEG',
 'Art. 17 FIDLEV',
 'Art. 14 Abs. 2 FIDLEG',
 'Art. 14 Abs. 3 FIDLEG',
 'Art. 398 Abs. 2 OR',
 'Art. 26 Abs. 3 FIDLEG',
 'Art. 400 OR',
 'Art. 26 FIDLEG',
 'Art. 26 Abs. 1 FIDLEG',
 'Art. 26 Abs. 2 FIDLEG',
 'Art. 25 Abs. 1 FIDLEG',
 'Art. 25 Abs. 2 FIDLEG',
 'Art. 25 Abs. 3 FIDLEG',
 'Art. 27 FIDLEV',
 'Art. 398 OR',
 'Art. 12 Abs. 1 DSG',
 'Art. 13 DSG',
 'Art. 13 Abs. 1 DSG',
 'Art. 204 Abs. 1 ZPO',
 'Art. 204 Abs. 3 ZPO',
 'Art. 68 Abs. 2 ZPO',
 'Art. 27 Abs. 1 SchKG',
 'Art. 20a Abs. 1 DBG',
 'Art. 16 Abs. 3 DBG',
 'Art. 20 Abs. 1 DBG',
 'Art. 216 Abs. 2 ZPO',
 'Art. 90 ZPO',
 'Art. 93 ZPO',
 'Art. 197 ZPO',
 'Art. 198 ZPO',
 'Art. 154 Abs. 4 FinfraG',
 'Art. 24 BV',
 'Art. 27 BV',
 'Art. 13 Abs. 1 BV',
 'Art. 10 Abs. 3 BV',
 'Art. 7 BV',
 'Art. 13 BV',
 'Art. 271 Abs. 1 SchKG',
 'Art. 271 Abs. 2 SchKG',
 'Art. 254 Abs. 1 ZPO',
 'Art. 29 Abs. 2 URG',
 'Art. 25 URG',
 'Art. 3 URG',
 'Art. 2 Abs. 1 URG',
 'Art. 11 Abs. 1 URG',
 'Art. 20 Abs. 1 DBG',
 'Art. 4 Abs. 1 VStG',
 'Art. 41 Abs. 1 OR',
 'Art. 969 Abs. 1 ZGB',
 'Art. 969 ZGB',
 'Art. 965 Abs. 1 ZGB',
 'Art. 968 ZGB',
 'Art. 144 StGB',
 'Art. 18 JStPO',
 'Art. 19 Abs. 2 JStPO',
 'Art. 130 StPO',
 'Art. 111 StGB',
 'Art. 22 Abs. 1 StGB',
 'Art. 48a StGB',
 'Art. 131 StPO',
 'Art. 131 Abs. 1 StPO',
 'Art. 131 Abs. 2 StPO',
 'Art. 307 Abs. 1 StPO',
 'Art. 131 Abs. 3 StPO',
 'Art. 141 Abs. 2 StPO',
 'BGE 141 IV 20 E. 1.1.4',
 'BGE 141 IV 289 E. 2.3',
 'Art. 175 Abs. 1 DBG',
 'Art. 181 Abs. 1 DBG',
 'Art. 176 DBG',
 'Art. 181 Abs. 3 DBG',
 'Art. 177 DBG',
 'Art. 186 Abs. 1 DBG',
 'Art. 60 IPRG',
 'Art. 64 IPRG',
 'Art. 1 LugÜ',
 'Art. 2 Abs. 1 LugÜ',
 'Art. 64 Abs. 1 IPRG',
 'Art. 59 IPRG',
 'Art. 65 Abs. 1 IPRG',
 'Art. 65 Abs. 2 IPRG',
 'Art. 64 Abs. 2 IPRG',
 'Art. 49 IPRG',
 'Art. 12 VwVG',
 'Art. 37 VGG',
 'Art. 20 Abs. 1 DBG',
 'Art. 7 Abs. 1 BankG',
 'Art. 8 Abs. 3 BankG',
 'Art. 36 Abs. 1 BV',
 'Art. 36 Abs. 1 BV',
 'Art. 5 Abs. 1 BV',
 'Art. 5 Abs. 2 BV',
 'Art. 36 Abs. 3 BV',
 'Art. 57 BV',
 'Art. 976 ZGB',
 'Art. 964 Abs. 1 ZGB',
 'Art. 736 Abs. 1 ZGB',
 'Art. 976a ZGB',
 'Art. 78 AIG',
 'Art. 646 Abs. 1 ZGB',
 'Art. 647 Abs. 1 ZG',
 'Art. 649a Abs. 1 ZGB',
 'Art. 745 Abs. 1 ZGB',
 'Art. 745 Abs. 3 ZGB',
 'Art. 753 Abs. 2 ZGB',
 'Art. 749 Abs. 2 ZGB',
 'Art. 779 Abs. 1 ZGB',
 'Art. 678 Abs. 2 ZGB',
 'Art. 781 Abs. 1 ZGB',
 'Art. 732 Abs. 2 ZGB',
 'Art. 144 StGB',
 'Art. 32 JStPO',
 'Art. 34 Abs. 1 JStPO',
 'Art. 15 JStG',
 'Art. 32 Abs. 1 JStPO',
 'Art. 6 Abs. 2 JStPO',
 'Art. 22 JStG',
 'Art. 23 JStG',
 'Art. 712d Abs. 2 ZGB',
 'Art. 712b Abs. 1 ZGB',
 'Art. 712d Abs. 3 ZGB',
 'Art. 712e Abs. 1 ZGB',
 'Art. 69 Abs. 1 GBV',
 'Art. 712d Abs. 1 ZGB',
 'Art. 963 Abs. 1 ZGB',
 'Art. 69 Abs. 2 GBV',
 'Art. 68 Abs. 2 GBV',
 'Art. 69 Abs. 3 GBV',
 'Art. 69 Abs. 4 GBV',
 'Art. 26 Abs. 2 HMG',
 'Art. 26 HMG',
 'Art. 65 ATSG',
 'Art. 37 Abs. 1 BV',
 'Art. 14 Abs. 2 IPRG',
 'Art. 37 Abs. 1 IPRG',
 'Art. 14 Abs. 1 IPRG',
 'Art. 243 Abs. 1 ZPO',
 'Art. 224 Abs. 1 ZPO',
 'Art. 62 BV',
 'Art. 201 OR',
 'Art. 203 OR',
 'Art. 20 Abs. 2 OR',
 'Art. 8 ZGB',
 'Art. 24 Abs. 1 OR',
 'Art. 31 OR',
 'Art. 24 OR',
 'Art. 187 Abs. 1 OR',
 'Art. 187 OR',
 'Art. 197 OR',
 'Art. 205 OR',
 'Art. 20 Abs. 1 OR',
 'Art. 23 OR',
 'Art. 63 Abs. 1 VwVG',
 'Art. 65 Abs. 1 VwVG',
 'Art. 63 Abs. 2 VwVG',
 'Art. 22 Abs. 2 RPG',
 'Art. 209 Abs. 3 ZPO',
 'Art. 111 Abs. 1 BGG',
 'Art. 33 Abs. 2 RPG',
 'Art. 89 Abs. 2 BGG',
 'Art. 12g Abs. 2 NHG',
 'Art. 111 Abs. 2 BGG',
 'Art. 106 Abs. 1 BGG',
 'Art. 22 Abs. 2 RPG',
 'Art. 24c RPG',
 'Art. 41 Abs. 1 RPV',
 'Art. 24c Abs. 2 RPG',
 'Art. 42 Abs. 1 RPV',
 'Art. 42 Abs. 2 RPV',
 'Art. 24c Abs. 4 RPG',
 'Art. 42 Abs. 3 RPV',
 'Art. 24c Abs. 5 RPG',
 'Art. 4 GSchG',
 'Art. 7 Abs. 1 GSchG',
 'BGE 134 III 565 E. 3.2',
 'Art. 47 EleG',
 'Art. 43 Abs. 1 LSV',
 'Art. 20 USG',
 'Art. 20 Abs. 1 USG',
 'Art. 15 Abs. 1 LSV',
 'Art. 2 Abs. 6 LSV',
 'Art. 20 Abs. 2 USG',
 'Art. 16 LSV',
 'Art. 58 Abs. 1 DBG',
 'Art. 13 Abs. 1 BV',
 'Art. 37 IRSG',
 'Art. 2 IRSG',
 'Art. 37 Abs. 1 IRSG',
 'Art. 85 Abs. 2 IRSG',
 'Art. 94 Abs. 1 IRSG',
 'Art. 85 Abs. 3 IRSG',
 'Art. 94 Abs. 2 IRSG',
 'Art. 8 Abs. 2 IRSV',
 'Art. 8 Abs. 1 IRSV',
 'Art. 140 StGB',
 'Art. 35 Abs. 1 IRSG',
 'Art. 94 IRSG',
 'BGE 129 II 100 E. 3.5',
 'Art. 150 Abs. 1 IPRG',
 'Art. 154 Abs. 1 IPRG',
 'Art. 3 Abs. 1 NHG',
 'Art. 3 Abs. 3 NHG',
 'Art. 89 BV',
 'Art. 17 IPRG',
 'Art. 27 IPRG',
 'Art. 837 Abs. 1 ZGB',
 'Art. 824 Abs. 1 ZGB',
 'Art. 832 Abs. 1 ZGB',
 'Art. 824 Abs. 2 ZGB',
 'Art. 832 Abs. 2 ZGB',
 'Art. 175 Abs. 1 OR',
 'Art. 176 Abs. 1 OR',
 'Art. 834 Abs. 1 ZGB',
 'Art. 24 RPG',
 'Art. 11 Abs. 1 RPG',
 'Art. 11 Abs. 2 RPV',
 'Art. 8a Abs. 1 RPG',
 'Art. 15 RPG',
 'Art. 15 Abs. 3 RPG',
 'Art. 3 RPG',
 'Art. 75 Abs. 1 BV',
 'Art. 1 RPG',
 'Art. 4 Abs. 1 VStG',
 'Art. 20 Abs. 1 VStV',
 'Art. 14 VStG',
 'Art. 20 Abs. 1 DBG',
 'Art. 2 Abs. 1 ZGB',
 'Art. 754 OR',
 'Art. 46 Abs. 1 KVV',
 'Art. 3 Abs. 2 BankG',
 'Art. 20 Abs. 3 VVG',
 'Art. 9 IPRG',
 'Art. 9 Abs. 2 IPRG',
 'Art. 3 DSG',
 'Art. 25 IPRG',
 'Art. 49 VwVG',
 'Art. 63a Abs. 3 BV',
 'Art. 45 Abs. 3 OR',
 'Art. 47 OR',
 'Art. 239 StGB',
 'Art. 41 Abs. 1 OR',
 'Art. 55 Abs. 1 OR',
 'Art. 41 Abs. 2 OR',
 'Art. 3 Abs. 2 BankG',
 'Art. 7 Abs. 1 FINMAG',
 'Art. 16 Abs. 3 DBG',
 'Art. 3 FINMAG',
 'Art. 33a FINMAG',
 'Art. 33 FINMAG',
 'Art. 34 FINMAG',
 'Art. 35 FINMAG',
 'Art. 154 Abs. 4 FinfraG',
 'Art. 145 FinfraG',
 'Art. 21 BV',
 'Art. 24 BV',
 'Art. 25 Abs. 1 BV',
 'Art. 27 BV',
 'Art. 136 Abs. 1 BV',
 'Art. 25 Abs. 2 BV',
 'Art. 8 BV',
 'Art. 13 Abs. 1 BV',
 'Art. 88 Abs. 1 BGG',
 'Art. 10 BV',
 'Art. 19 GUMG',
 'Art. 19 Abs. 3 GUMG',
 'Art. 37 Abs. 3 IVV',
 'Art. 757 Abs. 1 OR',
 'Art. 754 OR',
 'Art. 155 IPRG',
 'Art. 756 Abs. 1 OR',
 'Art. 325 SchKG',
 'Art. 288 Abs. 1 SchKG',
 'Art. 757 OR',
 'Art. 754 Abs. 1 OR',
 'Art. 41 OR',
 'Art. 717 Abs. 1 OR',
 'BGE 137 III 481 E. 2.1',
 'BGE 136 III 322 E. 3',
 'BGE 132 III 564 E. 6.2',
 'BGE 132 III 321 E. 2.2.1',
 'BGE 129 III 331 E. 2.1',
 'BGE 132 III 564 E. 3.1.2',
 'BGE 132 III 564 E. 3.1.3',
 'BGE 132 III 342 E. 2.3.3',
 'BGE 132 III 564 E. 3.2.2',
 'BGE 128 III 180 E. 2c',
 'BGE 132 III 564 E. 3.2.3',
 'BGE 141 III 112 E. 5.2.3',
 'BGE 131 III 306 E. 3.1.1',
 'BGE 132 III 564 E. 3.1',
 'BGE 131 III 306 E. 3.1.2',
 'BGE 132 III 564 E. 3.2.1',
 'BGE 141 III 112 E. 5.2.1',
 'BGE 132 III 342 E. 2.3.1',
 'BGE 132 III 342 E. 4.1',
 'Art. 343 StPO',
 'Art. 343 Abs. 1 StPO',
 'Art. 343 Abs. 2 StPO',
 'Art. 147 StPO',
 'Art. 343 Abs. 3 StPO',
 'Art. 3 Abs. 1 DBG',
 'Art. 3 Abs. 2 DBG',
 'Art. 3 Abs. 3 DBG',
 'Art. 45 BankV',
 'Art. 1a BankG',
 'Art. 5 Abs. 1 BankV',
 'Art. 64 Abs. 3 FIDLEG',
 'Art. 5 Abs. 3 BankV',
 'Art. 35 Abs. 1 FIDLEG',
 'Art. 3 Abs. 7 FIDLEV',
 'Art. 3 FIDLEG',
 'Art. 36 Abs. 1 FIDLEG',
 'Art. 6 Abs. 2 BankV',
 'Art. 1b Abs. 1 BankG',
 'Art. 1b Abs. 4 BankG',
 'Art. 2 UWG',
 'Art. 1 UWG',
 'Art. 136 Abs. 1 IPRG',
 'Art. 3 Abs. 1 UWG',
 'Art. 127 Abs. 2 BV',
 'Art. 35a Abs. 1 MVV',
 'Art. 37h BankG',
 'Art. 328b OR',
 'Art. 328 OR',
 'Art. 26 ArGV 3',
 'Art. 28 ZGB',
 'Art. 2a BetmG',
 'Art. 349a Abs. 2 OR',
 'Art. 324 OR',
 'Art. 18 Abs. 1 NHG',
 'Art. 6 TwwV',
 'Art. 6 Abs. 1 TwwV',
 'Art. 7 Abs. 1 TwwV',
 'Art. 68 Abs. 1 BV',
 'Art. 20 Abs. 1 NHG',
 'Art. 31 Abs. 4 BV',
 'Art. 3 DSG',
 'Art. 2 Abs. 2 DSG',
 'Art. 7 Abs. 1 DSG',
 'Art. 12 Abs. 2 DSG',
 'Art. 4 Abs. 4 DSG',
 'Art. 4 Abs. 2 DSG',
 'Art. 14 DSG',
 'Art. 14 Abs. 4 DSG',
 'Art. 11a Abs. 3 DSG',
 'Art. 59 Abs. 3 StGB',
 'Art. 76 Abs. 2 StGB',
 'Art. 59 StGB',
 'Art. 64 StGB',
 'Art. 82 Abs. 1 StPO',
 'Art. 65 StGB',
 'Art. 64 Abs. 1 StGB',
 'Art. 76 StGB',
 'Art. 59 Abs. 1 StGB',
 'Art. 62c Abs. 6 StGB',
 'Art. 59 Abs. 2 StGB',
 'Art. 64 Abs. 4 StGB',
 'Art. 19 Abs. 2 StPO',
 'Art. 439 Abs. 2 StPO',
 'Art. 228 Abs. 2 StPO',
 'Art. 30c Abs. 1 BVG',
 'Art. 30c Abs. 5 BVG',
 'Art. 30c Abs. 2 BVG',
 'Art. 30c Abs. 4 BVG',
 'Art. 398 Abs. 2 OR',
 'Art. 76b Abs. 1 SVG',
 'Art. 166 Abs. 1 IPRG',
 'Art. 25 USG',
 'Art. 25 Abs. 1 USG',
 'Art. 7 Abs. 1 LSV',
 'Art. 43 Abs. 1 LSV',
 'Art. 25 Abs. 2 USG',
 'Art. 7 Abs. 2 LSV',
 'Art. 25 Abs. 3 USG',
 'Art. 29 Abs. 1 BV',
 'Art. 7 Abs. 3 OR',
 'Art. 24 Abs. 1 OR',
 'Art. 26 OR',
 'Art. 7 OR',
 'Art. 1 Abs. 1 OR',
 'Art. 1 OR',
 'Art. 24 OR',
 'Art. 25 OR',
 'Art. 23 OR',
 'Art. 55 Abs. 1 USG',
 'Art. 12 Abs. 1 NHG',
 'Art. 78 Abs. 4 BV',
 'Art. 12 NHG',
 'Art. 78 Abs. 2 BV',
 'Art. 78 BV',
 'Art. 24 RPG',
 'Art. 12 Abs. 5 NHG',
 'Art. 12c Abs. 2 NHG',
 'Art. 839 Abs. 2 ZGB',
 'Art. 3 Abs. 1 JStPO',
 'Art. 163 Abs. 2 StPO',
 'Art. 168 Abs. 1 StPO',
 'Art. 83 BGG',
 'Art. 113 BGG',
 'Art. 2 Abs. 1 RPG',
 'Art. 23 Abs. 1 AIG',
 'Art. 68 AIG',
 'Art. 78 AIG',
 'Art. 25 StGB',
 'Art. 158 StGB',
 'Art. 143 FinfraG',
 'Art. 155 FinfraG',
 'Art. 655 Abs. 2 ZGB',
 'Art. 655 Abs. 3 ZGB',
 'Art. 678 Abs. 2 ZGB',
 'Art. 780 Abs. 3 ZGB',
 'Art. 781 ZGB',
 'Art. 7 Abs. 1 FINMAG',
 'Art. 7 Abs. 2 FINMAG',
 'Art. 83 AIG',
 'Art. 83 Abs. 3 AIG',
 'Art. 5 AsylG',
 'Art. 83 Abs. 7 AIG',
 'Art. 83 Abs. 9 AIG',
 'Art. 2 Abs. 1 LugÜ',
 'Art. 49 Abs. 1 VVEA',
 'Art. 31c USG',
 'Art. 9 SebG',
 'Art. 292 StGB',
 'Art. 55 Abs. 1 VwVG',
 'Art. 56 VwVG',
 'Art. 55 Abs. 3 VwVG',
 'Art. 22 Abs. 1 RPG',
 'Art. 55 Abs. 1 USG',
 'Art. 12 Abs. 1 NHG',
 'Art. 76 Abs. 3 BV',
 'Art. 91 Abs. 1 IPRG',
 'Art. 29 Abs. 1 ZPO',
 'Art. 9 Abs. 1 ZPO',
 'Art. 17 ZPO',
 'Art. 19 Abs. 1 FamZG',
 'Art. 19 Abs. 2 FamZG',
 'Art. 114 ZPO',
 'Art. 113 Abs. 2 ZPO',
 'Art. 86 ZPO',
 'Art. 25 Abs. 2 RPG',
 'Art. 25a RPG',
 'Art. 21 BV',
 'Art. 39 Abs. 1 BV',
 'Art. 51 Abs. 1 BV',
 'Art. 34 BV',
 'Art. 34 Abs. 2 BV',
 'Art. 471 ZGB',
 'Art. 608 Abs. 2 ZGB',
 'Art. 3 AIG',
 'Art. 15 ArG',
 'Art. 18 Abs. 3 ArGV 1',
 'Art. 21 Abs. 2 VStG',
 'Art. 21 Abs. 1 VStG',
 'Art. 6 ZPO',
 'Art. 6 Abs. 2 ZPO',
 'Art. 197 ZPO',
 'Art. 198 ZPO',
 'Art. 30 Abs. 2 USG',
 'Art. 11 VVEA',
 'Art. 134 StGB',
 'Art. 16a Abs. 2 JStG',
 'Art. 16a JStG',
 'Art. 29 Abs. 2 JStG',
 'Art. 955 Abs. 1 ZGB',
 'Art. 60 OR',
 'Art. 969 ZGB',
 'Art. 964 ZGB',
 'Art. 969 Abs. 1 ZGB',
 'Art. 955 Abs. 2 ZGB',
 'Art. 970 Abs. 3 ZGB',
 'Art. 26 Abs. 1 GBV',
 'Art. 970 Abs. 4 ZGB',
 'Art. 400 Abs. 1 OR',
 'Art. 712h Abs. 1 ZGB',
 'Art. 712i Abs. 1 ZGB',
 'Art. 712t Abs. 2 ZGB',
 'Art. 712i Abs. 3 ZGB',
 'Art. 799 Abs. 1 ZGB',
 'Art. 839 Abs. 3 ZGB',
 'Art. 961 Abs. 1 ZGB',
 'Art. 961 Abs. 2 ZGB',
 'Art. 76 Abs. 2 GBV',
 'Art. 961 Abs. 3 ZGB',
 'Art. 712i ZGB',
 'Art. 712k ZGB',
 'Art. 3 Abs. 2 BankG',
 'Art. 143 Abs. 1 StGB',
 'Art. 147 StGB',
 'Art. 844 Abs. 1 ZGB',
 'Art. 312 OR',
 'Art. 847 Abs. 1 ZGB',
 'Art. 816 Abs. 1 ZGB',
 'Art. 28 ZGB',
 'Art. 15 Abs. 1 DSG',
 'Art. 12 DSG',
 'Art. 10 BV',
 'Art. 13 BV',
 'Art. 14 BV',
 'Art. 3 Abs. 1 DBG',
 'Art. 9 Abs. 1 DBG',
 'Art. 296 Abs. 2 ZGB',
 'Art. 9 Abs. 2 DBG',
 'Art. 754 OR',
 'Art. 102 Abs. 2 StGB',
 'Art. 62 Abs. 2 VwVG',
 'Art. 46 Abs. 2 OR',
 'Art. 4 StromVV',
 'Art. 14 Abs. 1 StromVG',
 'Art. 24a RPG',
 'Art. 22 Abs. 1 RPG',
 'Art. 7 Abs. 1 KGTG',
 'Art. 24 Abs. 1 KGTG',
 'Art. 55 OR',
 'Art. 4 PrHG',
 'Art. 58 Abs. 1 DBG',
 'Art. 960a Abs. 1 OR',
 'Art. 960a Abs. 2 OR',
 'Art. 960b Abs. 1 OR',
 'Art. 9 GwG',
 'Art. 6 VStrR',
 'Art. 21 Abs. 2 RPG',
 'Art. 34 Abs. 1 ZPO',
 'Art. 202 ZPO',
 'Art. 13 IPRG',
 'Art. 11 Abs. 1 JStG',
 'Art. 3 Abs. 1 JStG',
 'Art. 4 JStG',
 'Art. 22 JStG',
 'Art. 23 JStG',
 'Art. 79a Abs. 3 StGB',
 'Art. 10 Abs. 3 StGB',
 'Art. 24 JStG',
 'Art. 25 JStG',
 'Art. 25 Abs. 2 JStG',
 'Art. 340c Abs. 2 OR',
 'Art. 340a OR',
 'Art. 4 UWG',
 'Art. 6 UWG',
 'Art. 1 UWG',
 'Art. 5 UWG',
 'Art. 2 UWG',
 'Art. 1 Abs. 2 IPRG',
 'Art. 1 Abs. 2 LugÜ',
 'Art. 2 Abs. 1 LugÜ',
 'Art. 779i Abs. 1 ZGB',
 'Art. 824 Abs. 2 ZGB',
 'Art. 794 Abs. 2 ZGB',
 'Art. 779k Abs. 1 ZGB',
 'Art. 779k Abs. 2 ZGB',
 'Art. 839 Abs. 3 ZGB',
 'Art. 816 Abs. 1 ZGB',
 'Art. 816 Abs. 2 ZGB',
 'Art. 175 DBG',
 'Art. 181 Abs. 1 DBG',
 'Art. 177 DBG',
 'Art. 181 Abs. 3 DBG',
 'Art. 176 DBG',
 'Art. 186 Abs. 1 DBG',
 'Art. 110 Abs. 4 StGB',
 'Art. 125 Abs. 2 DBG',
 'Art. 102 StGB',
 'Art. 25 StGB',
 'Art. 186 Abs. 2 DBG',
 'Art. 7 Abs. 1 UVG',
 'Art. 7 Abs. 2 UVG',
 'Art. 13 Abs. 1 UVV',
 'Art. 13 Abs. 2 UVV',
 'Art. 16 UVG',
 'Art. 59 StGB',
 'Art. 64 StGB',
 'Art. 19 StGB',
 'Art. 56 Abs. 2 StGB',
 'Art. 36 BV',
 'Art. 56 Abs. 1 StGB',
 'Art. 59 Abs. 4 StGB',
 'Art. 89 Abs. 2 BGG',
 'Art. 89 Abs. 1 BGG',
 'Art. 61 ATSG',
 'Art. 2 Abs. 5 KGTG',
 'Art. 7 Abs. 1 KGTG',
 'Art. 42a Abs. 2 FINMAG',
 'Art. 47 VwVG',
 'Art. 776 Abs. 1 ZGB',
 'Art. 776 Abs. 2 ZGB',
 'Art. 641 Abs. 2 ZGB',
 'Art. 737 Abs. 3 ZGB',
 'Art. 679 Abs. 1 ZGB',
 'Art. 684 Abs. 1 ZGB',
 'Art. 679a ZGB',
 'Art. 679 ZGB',
 'Art. 42 Abs. 2 FINMAG',
 'Art. 58 Abs. 1 DBG',
 'Art. 4 Abs. 1 VStG',
 'Art. 20 Abs. 1 VStV',
 'Art. 10 Abs. 1 VStG',
 'Art. 14 VStG',
 'Art. 23 VStG',
 'Art. 20 Abs. 3 DBG',
 'Art. 20 Abs. 1 DBG',
 'Art. 18b DBG',
 'Art. 118 OR',
 'Art. 121 OR',
 'Art. 127 OR',
 'Art. 131 Abs. 2 OR',
 'Art. 16a Abs. 1 RPG',
 'Art. 34 Abs. 2 RPV',
 'Art. 16a RPG',
 'Art. 24b RPG',
 'Art. 40 Abs. 3 RPV',
 'Art. 40 Abs. 4 RPV',
 'Art. 40 Abs. 1 RPV',
 'Art. 24b Abs. 1 RPG',
 'Art. 24b Abs. 2 RPG',
 'Art. 24a RPG',
 'Art. 22 RPG',
 'Art. 24c RPG',
 'Art. 37a RPG',
 'Art. 43 RPV',
 'Art. 43 Abs. 1 RPV',
 'Art. 356b OR',
 'Art. 9 GwG',
 'Art. 102 Abs. 1 StGB',
 'Art. 102 Abs. 2 StGB',
 'Art. 102 StGB',
 'Art. 754 OR',
 'Art. 25 Abs. 3 BV',
 'Art. 144 StGB',
 'Art. 32 Abs. 3 JStPO',
 'Art. 32 Abs. 4 JStPO',
 'Art. 32 Abs. 5 JStPO',
 'Art. 118 Abs. 1 StPO',
 'Art. 3 Abs. 1 JStPO',
 'Art. 138 Abs. 1 StGB',
 'Art. 158 Abs. 1 StGB',
 'Art. 69 ZGB',
 'Art. 59 Abs. 3 StGB',
 'Art. 64 Abs. 1 StGB',
 'Art. 64 StGB',
 'Art. 59 StGB',
 'Art. 6 ATSG',
 'Art. 82 SchKG',
 'Art. 217 ZPO',
 'Art. 336 Abs. 1 OR',
 'Art. 336a OR',
 'Art. 336b OR',
 'Art. 5 DBG',
 'Art. 9 UVG',
 'Art. 9 Abs. 1 UVG',
 'Art. 14 UVV',
 'Art. 9 Abs. 2 UVG',
 'Art. 1 Abs. 2 LugÜ',
 'Art. 87 Abs. 2 IPRG',
 'Art. 76a AIG',
 'Art. 79 AIG',
 'Art. 81 Abs. 2 AIG',
 'Art. 19 Abs. 1 FamZG',
 'Art. 64 Abs. 3 FIDLEG',
 'Art. 5 Abs. 3 BankV',
 'Art. 86 Abs. 2 IPRG',
 'Art. 123 StGB',
 'Art. 28 JStG',
 'Art. 24 RPG',
 'Art. 9 Abs. 1 RPG',
 'Art. 3 Abs. 1 JStG',
 'Art. 6 Abs. 2 JStPO',
 'Art. 10 Abs. 1 JStPO',
 'Art. 10 Abs. 3 JStPO',
 'Art. 23 ZGB',
 'Art. 218 Abs. 1 ZPO',
 'Art. 218 Abs. 2 ZPO',
 'Art. 105 BGG',
 'Art. 103 BGG',
 'Art. 76 BGG',
 'Art. 100 BGG',
 'Art. 714 Abs. 2 ZGB',
 'Art. 728 Abs. 1 ZGB',
 'Art. 8 ZGB',
 'Art. 9 Abs. 1 KGTG',
 'Art. 31 Abs. 1 OR',
 'Art. 213 Abs. 3 ZPO',
 'Art. 214 Abs. 3 ZPO',
 'Art. 813 Abs. 1 ZGB',
 'Art. 814 Abs. 3 ZGB',
 'Art. 959 Abs. 1 ZGB',
 'Art. 965 ZGB',
 'Art. 46 GBV',
 'Art. 965 Abs. 3 ZGB',
 'Art. 799 Abs. 2 ZGB',
 'Art. 78 Abs. 1 GBV',
 'Art. 965 Abs. 2 ZGB',
 'Art. 963 Abs. 1 ZGB',
 'Art. 84 Abs. 1 GBV',
 'Art. 9 Abs. 1 GBV',
 'Art. 123 Abs. 2 GBV',
 'Art. 123 Abs. 3 GBV',
 'Art. 946 Abs. 1 ZGB',
 'Art. 101 Abs. 3 GBV',
 'Art. 130 GBV',
 'Art. 176 IPRG',
 'Art. 18 OR',
 'Art. 177 IPRG',
 'Art. 181 IPRG',
 'Art. 47 Abs. 1 StGB',
 'Art. 959 Abs. 1 ZGB',
 'Art. 78 Abs. 3 GBV',
 'Art. 965 Abs. 3 ZGB',
 'Art. 77 Abs. 1 GBV',
 'Art. 963 Abs. 1 ZGB',
 'Art. 46 Abs. 1 GBV',
 'Art. 123 GBV',
 'Art. 261b Abs. 1 OR',
 'Art. 959 Abs. 2 ZGB',
 'Art. 961a ZGB',
 'Art. 261b Abs. 2 OR',
 'Art. 970 Abs. 4 ZGB',
 'Art. 41 Abs. 1 OR',
 'Art. 42 OR',
 'Art. 959 Abs. 2 OR',
 'Art. 960a Abs. 1 OR',
 'Art. 62 Abs. 1 DBG',
 'Art. 58 Abs. 1 DBG',
 'Art. 960a Abs. 2 OR',
 'Art. 960b Abs. 1 OR',
 'Art. 960e Abs. 2 OR',
 'Art. 960e Abs. 4 OR',
 'Art. 63 Abs. 2 DBG',
 'Art. 959a Abs. 5 OR',
 'Art. 842 Abs. 1 ZGB',
 'Art. 843 ZGB',
 'Art. 860 Abs. 2 ZGB',
 'Art. 860 Abs. 1 ZGB',
 'Art. 118 Abs. 1 OR',
 'Art. 118 Abs. 3 OR',
 'Art. 842 Abs. 2 ZGB',
 'Art. 312 OR',
 'Art. 11 Abs. 1 OR',
 'Art. 864 Abs. 1 ZG',

**Check data against provided corpus**

In [ ]:
train_citations_set = set(all_citations.unique())

articles_in_laws = set(laws_data['citation'].values)
articles_in_courts = set(court_csv['citation'].values)

In [ ]:
intersect_laws = train_citations_set.intersection(articles_in_laws)
non_intersect_laws = train_citations_set.difference(articles_in_laws)
intersect_courts = train_citations_set.intersection(articles_in_courts)
non_intersect_courts = train_citations_set.difference(articles_in_courts)

In [14]:
print(f"In laws: {len(articles_in_laws)}")
print(f"In courts: {len(articles_in_courts)}")
print(f"In training data intersection with laws: {len(intersect_laws)}")
print(f"In training data intersection with courts: {len(intersect_courts)}")
print(f"Not in laws: {len(non_intersect_laws)}")
print(f"Not in courts: {len(non_intersect_courts)}")

In laws: 175933
In courts: 1985178
In training data intersection with laws: 1876
In training data intersection with courts: 52
Not in laws: 819
Not in courts: 2643

There are some cases in training where the articles are not in the corpus and also not in val set - consider dropping them.

In [16]:
in_training_not_in_laws_not_in_courts = train_citations_set.difference(articles_in_laws.union(articles_in_courts))
print(f"In training data but not in laws or courts: {len(in_training_not_in_laws_not_in_courts)}")
print(",".join(list(in_training_not_in_laws_not_in_courts)))

In training data but not in laws or courts: 767
Art. 217 StPO,Art. 24a RPG,Art. 395 ZGB,Art. 522 ZGB,Art. 181 DBG,Art. 3 Abs. 3 StPO,Art. 549 ZGB,Art. 68 AIG,Art. 652 OR,Art. 659 OR,Art. 23 VStG,Art. 282 StGB,Art. 660 OR,Art. 25 URG,Art. 28 OR,Art. 27 ArG,Art. 712c ZGB,Art. 195a ZGB,Art. 28a ZGB,Art. 24 BV,Art. 476 ZGB,Art. 190 StGB,Art. 47 EleG,Art. 31c USG,Art. 5 GBV,Art. 13 JStG,Art. 18k EBG,Art. 41 OR,Art. 58 FIDLEG,Art. 3 DSG,Art. 61 Abs. 1 URG,Art. 18a DSG,Art. 257 ZPO,Art. 108 AsylG,Art. 5 Abs. 1 FIDLEG,Art. 28 JStG,Art. 706 OR,Art. 264m StGB,Art. 470 ZGB,Art. 12 ArG,Art. 23 JStG,Art. 209 ZGB,Art. 732 ZGB,Art. 138 StGB,Art. 15 Abs. 1 HKsÜ,Art. 96 IPRG,Art. 31 OR,Art. 419 Abs. 1 OR,Art. 15 JStG,Art. 9 UVG,Art. 100 SVG,Art. 15 RPG,Art. 66a StGB,Art. 177 DBG,Art. 83 GBV,Art. 34 Abs. 2 RPV,Art. 9 RPG,Art. 21 IPRG,Art. 11a Abs. 2 DSG,Art. 36 BV,Art. 237 ZPO,Art. 34 DSG,Art. 260 StPO,Art. 493 ZGB,Art. 3 URG,Art. 8 AsylG,Art. 186 DBG,Art. 24b RPG,Art. 9 JStPO,Art. 647d ZGB,Art. 210 OR,Art. 87 FIDLEG,Art. 187 OR,Art. 16 GBV,Art. 4a VStG,Art. 975 ZGB,Art. 86a ZGB,Art. 527 Abs. 4 ZGB,Art. 492a ZGB,Art. 100 AIG,Art. 712i ZGB,Art. 33 FINMAG,Art. 263 StGB,Art. 59 StGB,Art. 38 FINMAG,Art. 483 ZGB,Art. 17 BV,Art. 62a RVOG,Art. 158 ZPO,Art. 60 LugÜ,Art. 108 SchKG,Art. 90 IPRG,Art. 112 OR,Art. 849 ZGB,Art. 105 BGG,Art. 45 IPRG,Art. 216 OR,Art. 8 BV,Art. 559 ZGB,Art. 14 DSG,Art. 842 ZGB,Art. 225 ZGB,Art. 260 SchKG,Art. 26 HMG,Art. 241 ZGB,Art. 20 Abs. 1 VST,Art. 73 BPR,Art. 19 BetmG,Art. 474 ZGB,Art. 718a OR,Art. 84 GBV,Art. 31 FINMAG,Art. 24c RPG,Art. 801 ZGB,Art. 49 Abs. 1 VVEA,Art. 85a AIG,Art. 65a IRSG,Art. 112 IPRG,Art. 8 StGB,Art. 679 ZGB,Art. 279 ZGB,Art. 306 StPO,Art. 29 URG,Art. 12 JStG,Art. 260 ZPO,Art. 21 AIG,Art. 20 IPRG,Art. 27 Abs. 4 DSG,Art. 321a OR,Art. 443 ZGB,Art. 488 ZGB,Art. 83 IPRG,Art. 6 FINIG,Art. 408 ZGB,Art. 84 OR,Art. 15 Abs. 1 LugÜ,Art. 668 ZGB,Art. 46 Abs. 1 KVV,Art. 78 FIDLEG,Art. 101 OR,Art. 6 TwwV,Art. 41a USG,Art. 64 GBV,Art. 13 KFG,Art. 655a ZGB,Art. 27 ZGB,Art. 29 BEG,Art. 15 HMG,Art. 17 SchKG,Art. 1 MSchG,Art. 91a SVG,Art. 118 StPO,Art. 12 DBG,Art. 152 GBV,Art. 20a IRSG,Art. 97 GBV,Art. 43 Abs. 1 RPV,Art. 78 AIG,Art. 1085 OR,Art. 107a AsylG,Art. 58 DBG,Art. 1 RPG,Art. 23 LugÜ,Art. 321e OR,Art. 362 ZGB,Art. 91 SVG,Art. 50 PatG,Art. 243 ZPO,Art. 130 GBV,Art. 26 WV,Art. 969 ZGB,Art. 52 FINIG,Art. 93 BGG,Art. 94 GBV,Art. 479 ZGB,Art. 176 DBG,Art. 3 MSchG,Art. 8 RAG,Art. 12 DSG,Art. 190 Abs. 2 ZPO,Art. 44 OR,Art. 21 BVG,Art. 180 StGB,Art. 126 FinfraV,Art. 46 VwVG,Art. 79a StGB,Art. 61 StGB,Art. 336a OR,Art. 77b StGB,Art. 9 BüG,Art. 647b ZGB,Art. 495 ZGB,Art. 37 IRSG,Art. 98 GBV,Art. 5 IPRG,Art. 184 StGB,Art. 7 OBV,Art. 946 ZGB,Art. 52 ZGB,Art. 32 BV,Art. 151 FinfraG,Art. 20 USG,Art. 426 ZGB,Art. 7 RAG,Art. 5 ChemG,Art. 2 FIDLEG,Art. 155 FinfraG,Art. 239 StGB,Art. 12 JStPO,Art. 116 OR,Art. 36a KKG,Art. 18 OR,Art. 144 StGB,Art. 205 OR,Art. 42 OR,Art. 27 DSG,Art. 757 OR,Art. 33 OR,Art. 22 BV,Art. 113 StPO,Art. 8 AVIG,Art. 4 Abs. 4 DSG,Art. 140 StGB,Art. 469 ZGB,Art. 66 FINIG,Art. 3 ZGB,Art. 6 ZPO,Art. 655 ZGB,Art. 32 VGG,Art. 25 USG,Art. 4 StromVV,Art. 680 OR,Art. 48a StGB,Art. 960e OR,Art. 16 EleG,Art. 28 URG,Art. 477 Abs. 1 ZGB,Art. 34 ZPO,Art. 177 IPRG,Art. 361 OR,Art. 967 OR,Art. 3 AsylG,Art. 299 StPO,Art. 111 BGG,Art. 659 Abs. 5 OR,Art. 27 FinfraG,Art. 15 StromVG,Art. 3 BEG,Art. 98 IPRG,Art. 149c IPRG,Art. 23 ZGB,Art. 206 ZGB,Art. 1a MVG,Art. 24 UVG,Art. 12 BüG,Art. 102 StGB,Art. 494 ZGB,Art. 45 BankV,Art. 26 BankG,Art. 215 ZGB,Art. 423 OR,Art. 959 ZGB,Art. 27 Abs. 5 DSG,Art. 317 StGB,Art. 182 ZGB,Art. 11 PrHG,Art. 71 VwVG,Art. 26a VStV,Art. 100 BGG,Art. 58 SVG,Art. 29 OR,Art. 398 OR,Art. 127 BV,Art. 125 ZGB,Art. 9 Abs. 5 DSG,Art. 357 OR,Art. 282 StPO,Art. 49 GBV,Art. 9 IPRG,Art. 32 JStPO,Art. 949a ZGB,Art. 86 BGG,Art. 23 Abs. 5 LugÜ,Art. 12 SVKG,Art. 51 ATSG,Art. 19 Abs. 3 GUMG,Art. 357b OR,Art. 10a USG,Art. 34 FINMAG,Art. 3 RPG,Art. 116 IPRG,Art. 294 StGB,Art. 72 StGB,Art. 712g ZGB,Art. 956a ZGB,Art. 63 AIG,Art. 336 OR,Art. 83 AsylG,Art. 1 OR,Art. 18a EBG,Art. 20 OR,Art. 236 ZPO,Art. 308 ZPO,Art. 17 DSG,Art. 15 URG,Art. 212 ZPO,Art. 725 OR,Art. 972 ZGB,Art. 1 Abs. 2 LugÜ,Art. 647a ZGB,Art. 340a OR,Art. 271 SchKG,Art. 965 ZGB,Art. 258 ZPO,Art. 17 FIDLEV,Art. 31b AsylG,Art. 644 OR,Art. 4 VStG,Art. 482 ZGB,Art. 32 OR,Art. 52 ATSG,Art. 12 URG,Art. 79 StGB,Art. 10 ArG,Art. 321c OR,Art. 13 DSG,Art. 50 GBV,Art. 13 RPG,Art. 27 BV,Art. 32 FINMAG,Art. 60 VVG,Art. 55 OR,Art. 56 Abs. 1 DBG,Art. 63 URG,Art. 17 JStPO,Art. 264 StPO,Art. 16 BV,Art. 174 StGB,Art. 183 ZPO,Art. 27 BEG,Art. 177 Abs. 1 ZPO,Art. 31 GBV,Art. 205 ZGB,Art. 15 Abs. 2 LugÜ,Art. 26 OR,Art. 55a KVG,Art. 4 Abs. 3 DSG,Art. 237 StGB,Art. 718 OR,Art. 103 BGG,Art. 80p IRSG,Art. 141 StPO,Art. 50 BV,Art. 160 GBV,Art. 147 StPO,Art. 35 OR,Art. 82 SchKG,Art. 62 AIG,Art. 55 ZPO,Art. 608 ZGB,Art. 31 BV,Art. 19a BetmG,Art. 257 Abs. 1 ZPO,Art. 123 StGB,Art. 6 NHG,Art. 58 VwVG,Art. 1 VBVV,Art. 21 JStG,Art. 24 BEG,Art. 94 IRSG,Art. 19 StGB,Art. 15 FIDLEG,Art. 65 IPRG,Art. 93 SchKG,Art. 492 ZGB,Art. 336b OR,Art. 156 FinfraG,Art. 948 ZGB,Art. 18b DBG,Art. 32a USG,Art. 730 ZGB,Art. 34 Abs. 1 RPV,Art. 65 GBV,Art. 22 RPG,Art. 234 ZPO,Art. 85 IPRG,Art. 30 BüV,Art. 25 BankG,Art. 324 OR,Art. 681a ZGB,Art. 64 IPRG,Art. 1028 OR,Art. 62 BV,Art. 16a JStG,Art. 852 ZGB,Art. 1a UVG,Art. 17 DBG,Art. 9 SVKG,Art. 9 UWG,Art. 979 OR,Art. 360 ZGB,Art. 14 VStG,Art. 9 RAG,Art. 69 ZGB,Art. 19 DSG,Art. 1 LugÜ,Art. 8 StPO,Art. 76 StGB,Art. 859 ZGB,Art. 7 URG,Art. 5 DBG,Art. 70 IRSG,Art. 647e ZGB,Art. 6 GBV,Art. 936 ZGB,Art. 58a AIG,Art. 168 StPO,Art. 682 ZGB,Art. 81 GBV,Art. 630 ZGB,Art. 23 UWG,Art. 62 KVG,Art. 79 AIG,Art. 131 GBV,Art. 197 StPO,Art. 45 OR,Art. 388 ZGB,Art. 328 OR,Art. 144 GBV,Art. 175 DBG,Art. 356b OR,Art. 9 URG,Art. 862 ZGB,Art. 76a AIG,Art. 11 URG,Art. 221 StPO,Art. 8a SchKG,Art. 202 ZPO,Art. 64 KVG,Art. 16a RPG,Art. 4 Abs. 5 DSG,Art. 332 StGB,Art. 16 UVG,Art. 63 DBG,Art. 864 Abs. 1 ZG,Art. 28 BEG,Art. 60 OR,Art. 118 OR,Art. 736 OR,Art. 3 UEG,Art. 15 DSG,Art. 43 AsylG,Art. 158 StGB,Art. 4 GwG,Art. 3a Abs. 1 BankG,Art. 185 BV,Art. 182 BV,Art. 343 StPO,Art. 59 Abs. 1 LugÜ,Art. 140 StPO,Art. 121a BV,Art. 13 SebG,Art. 97 OR,Art. 678 OR,Art. 27 IPRG,Art. 191 ZPO,Art. 27 WV,Art. 11 TEVG,Art. 325 ZGB,Art. 47 StGB,Art. 208 ZGB,Art. 955 ZGB,Art. 967 ZGB,Art. 6 StPO,Art. 40e PatG,Art. 34 BV,Art. 285 StGB,Art. 9 DesG,Art. 10a Abs. 1 UVG,Art. 10 UVG,Art. 4 PrHG,Art. 647 Abs. 1 ZG,Art. 14 VVG,Art. 55 MSchG,Art. 67 OR,Art. 10 HKsÜ,Art. 197 ZGB,Art. 322d OR,Art. 85 ZPO,Art. 31 GSchG,Art. 25a VwVG,Art. 14 Abs. 4 DSG,Art. 389 ZGB,Art. 37m BankG,Art. 95 SchKG,Art. 136 IPRG,Art. 77 BGG,Art. 40 RPV,Art. 16 Abs. 1 LugÜ,Art. 27 EOG,Art. 1a AHVG,Art. 9 GwG,Art. 204 ZGB,Art. 512 ZGB,Art. 2 WG,Art. 3 OBG,Art. 5 RAG,Art. 139 StGB,Art. 146 StGB,Art. 19 URG,Art. 15 IPRG,Art. 6 BankV,Art. 50 OR,Art. 473 ZGB,Art. 237 StPO,Art. 154 IPRG,Art. 66d StGB,Art. 42 StGB,Art. 176 IPRG,Art. 55 AsylG,Art. 763 OR,Art. 458 ZGB,Art. 21 Abs. 3 UEG,Art. 37 IPRG,Art. 698 OR,Art. 2 Abs. 1 LugÜ,Art. 34 Abs. 3 RPV,Art. 41 LFG,Art. 970 ZGB,Art. 130 ZPO,Art. 354 StPO,Art. 143 StPO,Art. 65 StGB,Art. 9 SebG,Art. 123 GBV,Art. 322 ZGB,Art. 199 ZGB,Art. 198 StGB,Art. 168 Abs. 1 ZPO,Art. 2 LugÜ,Art. 643 OR,Art. 64 StGB,Art. 27 FIDLEV,Art. 7 OBG,Art. 22 SchKG,Art. 48 VwVG,Art. 23 StHG,Art. 934 ZGB,Art. 60a GSchG,Art. 348b OR,Art. 12 StHG,Art. 34 Abs. 4 RPV,Art. 977 ZGB,Art. 36 FINMAG,Art. 69 StGB,Art. 15 ArG,Art. 529 ZGB,Art. 1 Abs. 1 LugÜ,Art. 229 ZPO,Art. 11a Abs. 3 DSG,Art. 674 ZGB,Art. 36 FIDLEG,Art. 445 ZGB,Art. 61 KVG,Art. 75 BGG,Art. 58b AIG,Art. 39 KVG,Art. 62 OR,Art. 118 ZPO,Art. 13b Abs. 1 URG,Art. 106 StGB,Art. 6 VStrR,Art. 7 VAV,Art. 19 DesG,Art. 16b EOG,Art. 864 ZGB,Art. 335 ZGB,Art. 26 FIDLEG,Art. 50 FINMAG,Art. 16 LSV,Art. 46 ERV,Art. 68 BPR,Art. 964 ZGB,Art. 754 OR,Art. 43 RPV,Art. 31 StPO,Art. 49 StGB,Art. 2 NHG,Art. 38 VAG,Art. 129 GBV,Art. 5 VwVG,Art. 39 URG,Art. 57 MSchG,Art. 271 StGB,Art. 755 OR,Art. 6 RAG,Art. 78 BV,Art. 25 OR,Art. 27 AIG,Art. 2 URG,Art. 9 GBV,Art. 321 StGB,Art. 18 VFP,Art. 2 ZGB,Art. 265a SchKG,Art. 25a RPG,Art. 86 IPRG,Art. 67 URG,Art. 179 StGB,Art. 717 OR,Art. 26 ArGV 3,Art. 80 SchKG,Art. 70 StPO,Art. 14 JStG,Art. 715 ZGB,Art. 62 URG,Art. 83 AIG,Art. 47 VwVG,Art. 7 KGTG,Art. 72 BV,Art. 11 VVEA,Art. 216 ZGB,Art. 28 AHVV,Art. 37 FINMAG,Art. 177 StGB,Art. 37 FIDLEG,Art. 36 PatG,Art. 337c OR,Art. 13 OR,Art. 46 GBV,Art. 254 ZPO,Art. 239 OR,Art. 489 ZGB,Art. 19 LugÜ,Art. 37h BankG,Art. 3 ATSG,Art. 152 ZPO,Art. 150 ZPO,Art. 5 Abs. 1 DSG,Art. 11 OR,Art. 17 ZPO,Art. 19 FINIV,Art. 973 ZGB,Art. 366 ZGB,Art. 9 JStG,Art. 781 ZGB,Art. 93 ZPO,Art. 21 OR,Art. 625 OR,Art. 13b URG,Art. 2 RPG,Art. 28 IVG,Art. 18 BankG,Art. 101 KVV,Art. 53 NBG,Art. 400 OR,Art. 5 LugÜ,Art. 462 OR,Art. 7 OR,Art. 5 AsylG,Art. 477 Abs. 2 ZGB,Art. 2 OBG,Art. 55 VwVG,Art. 741 ZGB,Art. 147 StGB,Art. 18m EBG,Art. 963 ZGB,Art. 484 ZGB,Art. 222 ZGB,Art. 137 Abs. 5 WRV,Art. 725a OR,Art. 14a HMG,Art. 12 SebG,Art. 154 FinfraG,Art. 62b RVOG,Art. 33a URG,Art. 90 ZPO,Art. 675 OR,Art. 197 OR,Art. 92 SVG,Art. 959a Abs. 5 OR,Art. 137 Abs. 3 WRV,Art. 51 GBV,Art. 120 FinfraG,Art. 10 JStPO,Art. 884 ZGB,Art. 762 OR,Art. 13 BV,Art. 42 BV,Art. 74a IRSG,Art. 14 IPRG,Art. 30 DBG,Art. 7 SVG,Art. 37 GwG,Art. 190 IPRG,Art. 28 ZGB,Art. 3 AIG,Art. 10 BV,Art. 40 PatG,Art. 18 UVG,Art. 62 ZPO,Art. 13 URG,Art. 89 BV,Art. 57 BV,Art. 15 BV,Art. 265 SchKG,Art. 374 ZGB,Art. 35 FIDLEG,Art. 9 ZGB,Art. 22 DSG,Art. 8 DSG,Art. 49 OR,Art. 12 NHG,Art. 88 GBV,Art. 337 OR,Art. 634 ZGB,Art. 35 FINMAG,Art. 3 BankG,Art. 2 PatG,Art. 87 GBV,Art. 25 JStG,Art. 11 StGB,Art. 24 JStG,Art. 33a FINMAG,Art. 131 StPO,Art. 8 Abs. 5 DSG,Art. 31 DBG,Art. 57 StHG,Art. 513 ZGB,Art. 143 FinfraG,Art. 22 LugÜ,Art. 64 Abs. 1 LugÜ,Art. 38 FIDLEG,Art. 25 Abs. 1 IPRG,Art. 502 ZGB,Art. 976a ZGB,Art. 62 Abs. 3 AIG,Art. 281 StGB,Art. 971 ZGB,Art. 59 DBG,Art. 24 OR,Art. 33 GSchG,Art. 201 OR,Art. 10 URG,Art. 22 JStG,Art. 517 ZGB,Art. 973c OR,Art. 80 GBV,Art. 119 StGB,Art. 61 AsylG,Art. 721 Abs. 2 OR,Art. 7 VStrR,Art. 24 LugÜ,Art. 5 Abs. 2 LugÜ,Art. 684 ZGB,Art. 973d OR,Art. 190 DBG,Art. 42 AIG,Art. 18 EBG,Art. 17 ArG,Art. 251 StGB,Art. 119 BGG,Art. 183 StGB,Art. 76 BGG,Art. 79 Abs. 1 BV,Art. 66 ATSG,Art. 18w EBG

In [17]:
val_data = pd.read_csv(VAL_CSV)
val_data.head(5)

,query_id,query,gold_citations
0,val_001,May a court lawfully order a three‑month exten...,Art. 221 Abs. 1 StPO;Art. 140 Abs. 1 StGB;Art....
1,val_002,A claimant holding a national vocational diplo...,Art. 8 Abs. 1 ATSG;Art. 8 Abs. 1 IVG;Art. 17 A...
2,val_003,"A. Rivera, a Peruvian national born in 1994 an...",Art. 29 Abs. 2 BV;Art. 221 Abs. 1 StPO;Art. 39...
3,val_004,"Mr. Dalton, born in 1941 and resident in a sma...",Art. 505 Abs. 1 ZGB;Art. 467 ZGB;Art. 469 Abs....
4,val_005,"A parent, separated from their co-parent since...",Art. 133 Abs. 1 ZGB;Art. 133 Abs. 2 ZGB;Art. 2...

In [18]:
test_data = pd.read_csv(TEST_CSV)
test_data.head(5)

   query_id                                              query
0  test_001  Four U.S.-based software companies (NorthWave ...
1  test_002  On 9 August 2011 a 62‑year‑old cyclist (the cl...
2  test_003  On 12 March 2012, Meridian Leasing Ltd and Ori...
3  test_004  A publicly listed manufacturing company, Orion...
4  test_005  A logistics company (R Ltd.), which owns a dis...

In [19]:
val_not_in_laws_not_in_courts = set(val_data['gold_citations'].str.split(';').explode().str.strip().unique()).difference(articles_in_laws.union(articles_in_courts))
print(f"In validation data but not in laws or courts: {len(val_not_in_laws_not_in_courts)}")

In validation data but not in laws or courts: 0

In [20]:
val_in_training_not_in_laws_not_in_courts = set(val_data['gold_citations'].str.split(';').explode().str.strip().unique()).intersection(in_training_not_in_laws_not_in_courts)
print(f"In validation data and in training data but not in laws or courts: {len(val_in_training_not_in_laws_not_in_courts)}")

In validation data and in training data but not in laws or courts: 0

In [21]:
in_training_not_in_laws_not_in_courts

{'Art. 1 Abs. 1 LugÜ',
 'Art. 1 Abs. 2 LugÜ',
 'Art. 1 LugÜ',
 'Art. 1 MSchG',
 'Art. 1 OR',
 'Art. 1 RPG',
 'Art. 1 VBVV',
 'Art. 10 ArG',
 'Art. 10 BV',
 'Art. 10 HKsÜ',
 'Art. 10 JStPO',
 'Art. 10 URG',
 'Art. 10 UVG',
 'Art. 100 AIG',
 'Art. 100 BGG',
 'Art. 100 SVG',
 'Art. 101 KVV',
 'Art. 101 OR',
 'Art. 102 StGB',
 'Art. 1028 OR',
 'Art. 103 BGG',
 'Art. 105 BGG',
 'Art. 106 StGB',
 'Art. 107a AsylG',
 'Art. 108 AsylG',
 'Art. 108 SchKG',
 'Art. 1085 OR',
 'Art. 10a Abs. 1 UVG',
 'Art. 10a USG',
 'Art. 11 OR',
 'Art. 11 PrHG',
 'Art. 11 StGB',
 'Art. 11 TEVG',
 'Art. 11 URG',
 'Art. 11 VVEA',
 'Art. 111 BGG',
 'Art. 112 IPRG',
 'Art. 112 OR',
 'Art. 113 StPO',
 'Art. 116 IPRG',
 'Art. 116 OR',
 'Art. 118 OR',
 'Art. 118 StPO',
 'Art. 118 ZPO',
 'Art. 119 BGG',
 'Art. 119 StGB',
 'Art. 11a Abs. 2 DSG',
 'Art. 11a Abs. 3 DSG',
 'Art. 12 ArG',
 'Art. 12 BüG',
 'Art. 12 DBG',
 'Art. 12 DSG',
 'Art. 12 JStG',
 'Art. 12 JStPO',
 'Art. 12 NHG',
 'Art. 12 SVKG',
 'Art. 12 SebG',
 'Art. 12 StHG',
 'Art. 12 URG',
 'Art. 120 FinfraG',
 'Art. 121a BV',
 'Art. 123 GBV',
 'Art. 123 StGB',
 'Art. 125 ZGB',
 'Art. 126 FinfraV',
 'Art. 127 BV',
 'Art. 129 GBV',
 'Art. 13 BV',
 'Art. 13 DSG',
 'Art. 13 JStG',
 'Art. 13 KFG',
 'Art. 13 OR',
 'Art. 13 RPG',
 'Art. 13 SebG',
 'Art. 13 URG',
 'Art. 130 GBV',
 'Art. 130 ZPO',
 'Art. 131 GBV',
 'Art. 131 StPO',
 'Art. 136 IPRG',
 'Art. 137 Abs. 3 WRV',
 'Art. 137 Abs. 5 WRV',
 'Art. 138 StGB',
 'Art. 139 StGB',
 'Art. 13b Abs. 1 URG',
 'Art. 13b URG',
 'Art. 14 Abs. 4 DSG',
 'Art. 14 DSG',
 'Art. 14 IPRG',
 'Art. 14 JStG',
 'Art. 14 VStG',
 'Art. 14 VVG',
 'Art. 140 StGB',
 'Art. 140 StPO',
 'Art. 141 StPO',
 'Art. 143 FinfraG',
 'Art. 143 StPO',
 'Art. 144 GBV',
 'Art. 144 StGB',
 'Art. 146 StGB',
 'Art. 147 StGB',
 'Art. 147 StPO',
 'Art. 149c IPRG',
 'Art. 14a HMG',
 'Art. 15 Abs. 1 HKsÜ',
 'Art. 15 Abs. 1 LugÜ',
 'Art. 15 Abs. 2 LugÜ',
 'Art. 15 ArG',
 'Art. 15 BV',
 'Art. 15 DSG',
 'Art. 15 FIDLEG',
 'Art. 15 HMG',
 'Art. 15 IPRG',
 'Art. 15 JStG',
 'Art. 15 RPG',
 'Art. 15 StromVG',
 'Art. 15 URG',
 'Art. 150 ZPO',
 'Art. 151 FinfraG',
 'Art. 152 GBV',
 'Art. 152 ZPO',
 'Art. 154 FinfraG',
 'Art. 154 IPRG',
 'Art. 155 FinfraG',
 'Art. 156 FinfraG',
 'Art. 158 StGB',
 'Art. 158 ZPO',
 'Art. 16 Abs. 1 LugÜ',
 'Art. 16 BV',
 'Art. 16 EleG',
 'Art. 16 GBV',
 'Art. 16 LSV',
 'Art. 16 UVG',
 'Art. 160 GBV',
 'Art. 168 Abs. 1 ZPO',
 'Art. 168 StPO',
 'Art. 16a JStG',
 'Art. 16a RPG',
 'Art. 16b EOG',
 'Art. 17 ArG',
 'Art. 17 BV',
 'Art. 17 DBG',
 'Art. 17 DSG',
 'Art. 17 FIDLEV',
 'Art. 17 JStPO',
 'Art. 17 SchKG',
 'Art. 17 ZPO',
 'Art. 174 StGB',
 'Art. 175 DBG',
 'Art. 176 DBG',
 'Art. 176 IPRG',
 'Art. 177 Abs. 1 ZPO',
 'Art. 177 DBG',
 'Art. 177 IPRG',
 'Art. 177 StGB',
 'Art. 179 StGB',
 'Art. 18 BankG',
 'Art. 18 EBG',
 'Art. 18 OR',
 'Art. 18 UVG',
 'Art. 18 VFP',
 'Art. 180 StGB',
 'Art. 181 DBG',
 'Art. 182 BV',
 'Art. 182 ZGB',
 'Art. 183 StGB',
 'Art. 183 ZPO',
 'Art. 184 StGB',
 'Art. 185 BV',
 'Art. 186 DBG',
 'Art. 187 OR',
 'Art. 18a DSG',
 'Art. 18a EBG',
 'Art. 18b DBG',
 'Art. 18k EBG',
 'Art. 18m EBG',
 'Art. 18w EBG',
 'Art. 19 Abs. 3 GUMG',
 'Art. 19 BetmG',
 'Art. 19 DSG',
 'Art. 19 DesG',
 'Art. 19 FINIV',
 'Art. 19 LugÜ',
 'Art. 19 StGB',
 'Art. 19 URG',
 'Art. 190 Abs. 2 ZPO',
 'Art. 190 DBG',
 'Art. 190 IPRG',
 'Art. 190 StGB',
 'Art. 191 ZPO',
 'Art. 195a ZGB',
 'Art. 197 OR',
 'Art. 197 StPO',
 'Art. 197 ZGB',
 'Art. 198 StGB',
 'Art. 199 ZGB',
 'Art. 19a BetmG',
 'Art. 1a AHVG',
 'Art. 1a MVG',
 'Art. 1a UVG',
 'Art. 2 Abs. 1 LugÜ',
 'Art. 2 FIDLEG',
 'Art. 2 LugÜ',
 'Art. 2 NHG',
 'Art. 2 OBG',
 'Art. 2 PatG',
 'Art. 2 RPG',
 'Art. 2 URG',
 'Art. 2 WG',
 'Art. 2 ZGB',
 'Art. 20 Abs. 1 VST',
 'Art. 20 IPRG',
 'Art. 20 OR',
 'Art. 20 USG',
 'Art. 201 OR',
 'Art. 202 ZPO',
 'Art. 204 ZGB',
 'Art. 205 OR',
 'Art. 205 ZGB',
 'Art. 206 ZGB',
 'Art. 208 ZGB',
 'Art. 209 ZGB',
 'Art. 20a IRSG',
 'Art. 21 AIG',
 'Art. 21 Abs. 3 UEG',
 'Art. 21 BVG',
 'Art. 21 IPRG',
 'Art. 21 JStG',
 'Art. 21 OR',
 'Art. 210 OR',
 'Art. 212 ZPO',
 'Art. 215 ZGB',
 'Art. 216 OR',
 'Art. 216 ZGB',
 'Art. 217 StPO',
 'Art. 22 BV',
 'Art. 22 DSG',
 'Art. 22 JStG',
 'Art. 22 LugÜ',
 'Art. 22 RPG',
 'Art. 22 SchKG',
 'Art. 221 StPO',
 'Art. 222 ZGB',
 'Art. 225 ZGB',
 'Art. 229 ZPO',
 'Art. 23 Abs. 5 LugÜ',
 'Art. 23 JStG',
 'Art. 23 LugÜ',
 'Art. 23 StHG',
 'Art. 23 UWG',
 'Art. 23 VStG',
 'Art. 23 ZGB',
 'Art. 234 ZPO',
 'Art. 236 ZPO',
 'Art. 237 StGB',
 'Art. 237 StPO',
 'Art. 237 ZPO',
 'Art. 239 OR',
 'Art. 239 StGB',
 'Art. 24 BEG',
 'Art. 24 BV',
 'Art. 24 JStG',
 'Art. 24 LugÜ',
 'Art. 24 OR',
 'Art. 24 UVG',
 'Art. 241 ZGB',
 'Art. 243 ZPO',
 'Art. 24a RPG',
 'Art. 24b RPG',
 'Art. 24c RPG',
 'Art. 25 Abs. 1 IPRG',
 'Art. 25 BankG',
 'Art. 25 JStG',
 'Art. 25 OR',
 'Art. 25 URG',
 'Art. 25 USG',
 'Art. 251 StGB',
 'Art. 254 ZPO',
 'Art. 257 Abs. 1 ZPO',
 'Art. 257 ZPO',
 'Art. 258 ZPO',
 'Art. 25a RPG',
 'Art. 25a VwVG',
 'Art. 26 ArGV 3',
 'Art. 26 BankG',
 'Art. 26 FIDLEG',
 'Art. 26 HMG',
 'Art. 26 OR',
 'Art. 26 WV',
 'Art. 260 SchKG',
 'Art. 260 StPO',
 'Art. 260 ZPO',
 'Art. 263 StGB',
 'Art. 264 StPO',
 'Art. 264m StGB',
 'Art. 265 SchKG',
 'Art. 265a SchKG',
 'Art. 26a VStV',
 'Art. 27 AIG',
 'Art. 27 Abs. 4 DSG',
 'Art. 27 Abs. 5 DSG',
 'Art. 27 ArG',
 'Art. 27 BEG',
 'Art. 27 BV',
 'Art. 27 DSG',
 'Art. 27 EOG',
 'Art. 27 FIDLEV',
 'Art. 27 FinfraG',
 'Art. 27 IPRG',
 'Art. 27 WV',
 'Art. 27 ZGB',
 'Art. 271 SchKG',
 'Art. 271 StGB',
 'Art. 279 ZGB',
 'Art. 28 AHVV',
 'Art. 28 BEG',
 'Art. 28 IVG',
 'Art. 28 JStG',
 'Art. 28 OR',
 'Art. 28 URG',
 'Art. 28 ZGB',
 'Art. 281 StGB',
 'Art. 282 StGB',
 'Art. 282 StPO',
 'Art. 285 StGB',
 'Art. 28a ZGB',
 'Art. 29 BEG',
 'Art. 29 OR',
 'Art. 29 URG',
 'Art. 294 StGB',
 'Art. 299 StPO',
 'Art. 3 AIG',
 'Art. 3 ATSG',
 'Art. 3 Abs. 3 StPO',
 'Art. 3 AsylG',
 'Art. 3 BEG',
 'Art. 3 BankG',
 'Art. 3 DSG',
 'Art. 3 MSchG',
 'Art. 3 OBG',
 'Art. 3 RPG',
 'Art. 3 UEG',
 'Art. 3 URG',
 'Art. 3 ZGB',
 'Art. 30 BüV',
 'Art. 30 DBG',
 'Art. 306 StPO',
 'Art. 308 ZPO',
 'Art. 31 BV',
 'Art. 31 DBG',
 'Art. 31 FINMAG',
 'Art. 31 GBV',
 'Art. 31 GSchG',
 'Art. 31 OR',
 'Art. 31 StPO',
 'Art. 317 StGB',
 'Art. 31b AsylG',
 'Art. 31c USG',
 'Art. 32 BV',
 'Art. 32 FINMAG',
 'Art. 32 JStPO',
 'Art. 32 OR',
 'Art. 32 VGG',
 'Art. 321 StGB',
 'Art. 321a OR',
 'Art. 321c OR',
 'Art. 321e OR',
 'Art. 322 ZGB',
 'Art. 322d OR',
 'Art. 324 OR',
 'Art. 325 ZGB',
 'Art. 328 OR',
 'Art. 32a USG',
 'Art. 33 FINMAG',
 'Art. 33 GSchG',
 'Art. 33 OR',
 'Art. 332 StGB',
 'Art. 335 ZGB',
 'Art. 336 OR',
 'Art. 336a OR',
 'Art. 336b OR',
 'Art. 337 OR',
 'Art. 337c OR',
 'Art. 33a FINMAG',
 'Art. 33a URG',
 'Art. 34 Abs. 1 RPV',
 'Art. 34 Abs. 2 RPV',
 'Art. 34 Abs. 3 RPV',
 'Art. 34 Abs. 4 RPV',
 'Art. 34 BV',
 'Art. 34 DSG',
 'Art. 34 FINMAG',
 'Art. 34 ZPO',
 'Art. 340a OR',
 'Art. 343 StPO',
 'Art. 348b OR',
 'Art. 35 FIDLEG',
 'Art. 35 FINMAG',
 'Art. 35 OR',
 'Art. 354 StPO',
 'Art. 356b OR',
 'Art. 357 OR',
 'Art. 357b OR',
 'Art. 36 BV',
 'Art. 36 FIDLEG',
 'Art. 36 FINMAG',
 'Art. 36 PatG',
 'Art. 360 ZGB',
 'Art. 361 OR',
 'Art. 362 ZGB',
 'Art. 366 ZGB',
 'Art. 36a KKG',
 'Art. 37 FIDLEG',
 'Art. 37 FINMAG',
 'Art. 37 GwG',
 'Art. 37 IPRG',
 'Art. 37 IRSG',
 'Art. 374 ZGB',
 'Art. 37h BankG',
 'Art. 37m BankG',
 'Art. 38 FIDLEG',
 'Art. 38 FINMAG',
 'Art. 38 VAG',
 'Art. 388 ZGB',
 'Art. 389 ZGB',
 'Art. 39 KVG',
 'Art. 39 URG',
 'Art. 395 ZGB',
 'Art. 398 OR',
 'Art. 3a Abs. 1 BankG',
 'Art. 4 Abs. 3 DSG',
 'Art. 4 Abs. 4 DSG',
 'Art. 4 Abs. 5 DSG',
 'Art. 4 GwG',
 'Art. 4 PrHG',
 'Art. 4 StromVV',
 'Art. 4 VStG',
 'Art. 40 PatG',
 'Art. 40 RPV',
 'Art. 400 OR',
 'Art. 408 ZGB',
 'Art. 40e PatG',
 'Art. 41 LFG',
 'Art. 41 OR',
 'Art. 419 Abs. 1 OR',
 'Art. 41a USG',
 'Art. 42 AIG',
 'Art. 42 BV',
 'Art. 42 OR',
 'Art. 42 StGB',
 'Art. 423 OR',
 'Art. 426 ZGB',
 'Art. 43 Abs. 1 RPV',
 'Art. 43 AsylG',
 'Art. 43 RPV',
 'Art. 44 OR',
 'Art. 443 ZGB',
 'Art. 445 ZGB',
 'Art. 45 BankV',
 'Art. 45 IPRG',
 'Art. 45 OR',
 'Art. 458 ZGB',
 'Art. 46 Abs. 1 KVV',
 'Art. 46 ERV',
 'Art. 46 GBV',
 'Art. 46 VwVG',
 'Art. 462 OR',
 'Art. 469 ZGB',
 'Art. 47 EleG',
 'Art. 47 StGB',
 'Art. 47 VwVG',
 'Art. 470 ZGB',
 'Art. 473 ZGB',
 'Art. 474 ZGB',
 'Art. 476 ZGB',
 'Art. 477 Abs. 1 ZGB',
 'Art. 477 Abs. 2 ZGB',
 'Art. 479 ZGB',
 'Art. 48 VwVG',
 'Art. 482 ZGB',
 'Art. 483 ZGB',
 'Art. 484 ZGB',
 'Art. 488 ZGB',
 'Art. 489 ZGB',
 'Art. 48a StGB',
 'Art. 49 Abs. 1 VVEA',
 'Art. 49 GBV',
 'Art. 49 OR',
 'Art. 49 StGB',
 'Art. 492 ZGB',
 'Art. 492a ZGB',
 'Art. 493 ZGB',
 'Art. 494 ZGB',
 'Art. 495 ZGB',
 'Art. 4a VStG',
 'Art. 5 Abs. 1 DSG',
 'Art. 5 Abs. 1 FIDLEG',
 'Art. 5 Abs. 2 LugÜ',
 'Art. 5 AsylG',
 'Art. 5 ChemG',
 'Art. 5 DBG',
 'Art. 5 GBV',
 'Art. 5 IPRG',
 'Art. 5 LugÜ',
 'Art. 5 RAG',
 'Art. 5 VwVG',
 'Art. 50 BV',
 'Art. 50 FINMAG',
 'Art. 50 GBV',
 'Art. 50 OR',
 'Art. 50 PatG',
 'Art. 502 ZGB',
 'Art. 51 ATSG',
 'Art. 51 GBV',
 'Art. 512 ZGB',
 'Art. 513 ZGB',
 'Art. 517 ZGB',
 'Art. 52 ATSG',
 'Art. 52 FINIG',
 'Art. 52 ZGB',
 'Art. 522 ZGB',
 'Art. 527 Abs. 4 ZGB',
 'Art. 529 ZGB',
 'Art. 53 NBG',
 'Art. 549 ZGB',
 'Art. 55 AsylG',
 'Art. 55 MSchG',
 'Art. 55 OR',
 'Art. 55 VwVG',
 'Art. 55 ZPO',
 'Art. 559 ZGB',
 'Art. 55a KVG',
 'Art. 56 Abs. 1 DBG',
 'Art. 57 BV',
 'Art. 57 MSchG',
 'Art. 57 StHG',
 'Art. 58 DBG',
 'Art. 58 FIDLEG',
 'Art. 58 SVG',
 'Art. 58 VwVG',
 'Art. 58a AIG',
 'Art. 58b AIG',
 'Art. 59 Abs. 1 LugÜ',
 'Art. 59 DBG',
 'Art. 59 StGB',
 'Art. 6 BankV',
 'Art. 6 FINIG',
 'Art. 6 GBV',
 'Art. 6 NHG',
 'Art. 6 RAG',
 'Art. 6 StPO',
 'Art. 6 TwwV',
 'Art. 6 VStrR',
 'Art. 6 ZPO',
 'Art. 60 LugÜ',
 'Art. 60 OR',
 'Art. 60 VVG',
 'Art. 608 ZGB',
 'Art. 60a GSchG',
 'Art. 61 Abs. 1 URG',
 'Art. 61 AsylG',
 'Art. 61 KVG',
 'Art. 61 StGB',
 'Art. 62 AIG',
 'Art. 62 Abs. 3 AIG',
 'Art. 62 BV',
 'Art. 62 KVG',
 'Art. 62 OR',
 'Art. 62 URG',
 'Art. 62 ZPO',
 'Art. 625 OR',
 'Art. 62a RVOG',
 'Art. 62b RVOG',
 'Art. 63 AIG',
 'Art. 63 DBG',
 'Art. 63 URG',
 'Art. 630 ZGB',
 'Art. 634 ZGB',
 'Art. 64 Abs. 1 LugÜ',
 'Art. 64 GBV',
 'Art. 64 IPRG',
 'Art. 64 KVG',
 'Art. 64 StGB',
 'Art. 643 OR',
 'Art. 644 OR',
 'Art. 647 Abs. 1 ZG',
 'Art. 647a ZGB',
 'Art. 647b ZGB',
 'Art. 647d ZGB',
 'Art. 647e ZGB',
 'Art. 65 GBV',
 'Art. 65 IPRG',
 'Art. 65 StGB',
 'Art. 652 OR',
 'Art. 655 ZGB',
 'Art. 655a ZGB',
 'Art. 659 Abs. 5 OR',
 'Art. 659 OR',
 'Art. 65a IRSG',
 'Art. 66 ATSG',
 'Art. 66 FINIG',
 'Art. 660 OR',
 'Art. 668 ZGB',
 'Art. 66a StGB',
 'Art. 66d StGB',
 'Art. 67 OR',
 'Art. 67 URG',
 'Art. 674 ZGB',
 'Art. 675 OR',
 'Art. 678 OR',
 'Art. 679 ZGB',
 'Art. 68 AIG',
 'Art. 68 BPR',
 'Art. 680 OR',
 'Art. 681a ZGB',
 'Art. 682 ZGB',
 'Art. 684 ZGB',
 'Art. 69 StGB',
 'Art. 69 ZGB',
 'Art. 698 OR',
 'Art. 7 KGTG',
 'Art. 7 OBG',
 'Art. 7 OBV',
 'Art. 7 OR',
 'Art. 7 RAG',
 'Art. 7 SVG',
 'Art. 7 URG',
 'Art. 7 VAV',
 'Art. 7 VStrR',
 'Art. 70 IRSG',
 'Art. 70 StPO',
 'Art. 706 OR',
 'Art. 71 VwVG',
 'Art. 712c ZGB',
 'Art. 712g ZGB',
 'Art. 712i ZGB',
 'Art. 715 ZGB',
 'Art. 717 OR',
 'Art. 718 OR',
 'Art. 718a OR',
 'Art. 72 BV',
 'Art. 72 StGB',
 'Art. 721 Abs. 2 OR',
 'Art. 725 OR',
 'Art. 725a OR',
 'Art. 73 BPR',
 'Art. 730 ZGB',
 'Art. 732 ZGB',
 'Art. 736 OR',
 'Art. 741 ZGB',
 'Art. 74a IRSG',
 'Art. 75 BGG',
 'Art. 754 OR',
 'Art. 755 OR',
 'Art. 757 OR',
 'Art. 76 BGG',
 'Art. 76 StGB',
 'Art. 762 OR',
 'Art. 763 OR',
 'Art. 76a AIG',
 'Art. 77 BGG',
 'Art. 77b StGB',
 'Art. 78 AIG',
 'Art. 78 BV',
 'Art. 78 FIDLEG',
 'Art. 781 ZGB',
 'Art. 79 AIG',
 'Art. 79 Abs. 1 BV',
 'Art. 79 StGB',
 'Art. 79a StGB',
 'Art. 8 AVIG',
 'Art. 8 Abs. 5 DSG',
 'Art. 8 AsylG',
 'Art. 8 BV',
 'Art. 8 DSG',
 'Art. 8 RAG',
 'Art. 8 StGB',
 'Art. 8 StPO',
 'Art. 80 GBV',
 'Art. 80 SchKG',
 'Art. 801 ZGB',
 'Art. 80p IRSG',
 'Art. 81 GBV',
 'Art. 82 SchKG',
 'Art. 83 AIG',
 'Art. 83 AsylG',
 'Art. 83 GBV',
 'Art. 83 IPRG',
 'Art. 84 GBV',
 'Art. 84 OR',
 'Art. 842 ZGB',
 'Art. 849 ZGB',
 'Art. 85 IPRG',
 'Art. 85 ZPO',
 'Art. 852 ZGB',
 'Art. 859 ZGB',
 'Art. 85a AIG',
 'Art. 86 BGG',
 'Art. 86 IPRG',
 'Art. 862 ZGB',
 'Art. 864 Abs. 1 ZG',
 'Art. 864 ZGB',
 'Art. 86a ZGB',
 'Art. 87 FIDLEG',
 'Art. 87 GBV',
 'Art. 88 GBV',
 'Art. 884 ZGB',
 'Art. 89 BV',
 'Art. 8a SchKG',
 'Art. 9 Abs. 5 DSG',
 'Art. 9 BüG',
 'Art. 9 DesG',
 'Art. 9 GBV',
 'Art. 9 GwG',
 'Art. 9 IPRG',
 'Art. 9 JStG',
 'Art. 9 JStPO',
 'Art. 9 RAG',
 'Art. 9 RPG',
 'Art. 9 SVKG',
 'Art. 9 SebG',
 'Art. 9 URG',
 'Art. 9 UVG',
 'Art. 9 UWG',
 'Art. 9 ZGB',
 'Art. 90 IPRG',
 'Art. 90 ZPO',
 'Art. 91 SVG',
 'Art. 91a SVG',
 'Art. 92 SVG',
 'Art. 93 BGG',
 'Art. 93 SchKG',
 'Art. 93 ZPO',
 'Art. 934 ZGB',
 'Art. 936 ZGB',
 'Art. 94 GBV',
 'Art. 94 IRSG',
 'Art. 946 ZGB',
 'Art. 948 ZGB',
 'Art. 949a ZGB',
 'Art. 95 SchKG',
 'Art. 955 ZGB',
 'Art. 956a ZGB',
 'Art. 959 ZGB',
 'Art. 959a Abs. 5 OR',
 'Art. 96 IPRG',
 'Art. 960e OR',
 'Art. 963 ZGB',
 'Art. 964 ZGB',
 'Art. 965 ZGB',
 'Art. 967 OR',
 'Art. 967 ZGB',
 'Art. 969 ZGB',
 'Art. 97 GBV',
 'Art. 97 OR',
 'Art. 970 ZGB',
 'Art. 971 ZGB',
 'Art. 972 ZGB',
 'Art. 973 ZGB',
 'Art. 973c OR',
 'Art. 973d OR',
 'Art. 975 ZGB',
 'Art. 976a ZGB',
 'Art. 977 ZGB',
 'Art. 979 OR',
 'Art. 98 GBV',
 'Art. 98 IPRG'}

But they are found in "text" column in court data?

In [26]:
found = set()

for candidate in in_training_not_in_laws_not_in_courts:
    with open(COURTS_CSV, 'r', encoding="utf-8") as f:
        for line in f:
            if candidate in line:
                print(f"Candidatr {candidate} found in courts data.")
                found.add(candidate)
                break

Candidatr Art. 217 StPO found in courts data.
Candidatr Art. 24a RPG found in courts data.
Candidatr Art. 395 ZGB found in courts data.
Candidatr Art. 522 ZGB found in courts data.
Candidatr Art. 181 DBG found in courts data.
Candidatr Art. 68 AIG found in courts data.
Candidatr Art. 652 OR found in courts data.
Candidatr Art. 659 OR found in courts data.
Candidatr Art. 23 VStG found in courts data.
Candidatr Art. 282 StGB found in courts data.
Candidatr Art. 660 OR found in courts data.
Candidatr Art. 25 URG found in courts data.
Candidatr Art. 28 OR found in courts data.
Candidatr Art. 27 ArG found in courts data.
Candidatr Art. 712c ZGB found in courts data.
Candidatr Art. 195a ZGB found in courts data.
Candidatr Art. 28a ZGB found in courts data.
Candidatr Art. 24 BV found in courts data.
Candidatr Art. 476 ZGB found in courts data.
Candidatr Art. 190 StGB found in courts data.
Candidatr Art. 47 EleG found in courts data.
Candidatr Art. 31c USG found in courts data.
Candidatr Art. 13 JStG found in courts data.
Candidatr Art. 18k EBG found in courts data.
Candidatr Art. 41 OR found in courts data.
Candidatr Art. 3 DSG found in courts data.
Candidatr Art. 18a DSG found in courts data.
Candidatr Art. 257 ZPO found in courts data.
Candidatr Art. 706 OR found in courts data.
Candidatr Art. 264m StGB found in courts data.
Candidatr Art. 470 ZGB found in courts data.
Candidatr Art. 12 ArG found in courts data.
Candidatr Art. 23 JStG found in courts data.
Candidatr Art. 209 ZGB found in courts data.
Candidatr Art. 732 ZGB found in courts data.
Candidatr Art. 138 StGB found in courts data.
Candidatr Art. 15 Abs. 1 HKsÜ found in courts data.
Candidatr Art. 96 IPRG found in courts data.
Candidatr Art. 31 OR found in courts data.
Candidatr Art. 419 Abs. 1 OR found in courts data.
Candidatr Art. 15 JStG found in courts data.
Candidatr Art. 9 UVG found in courts data.
Candidatr Art. 100 SVG found in courts data.
Candidatr Art. 15 RPG found in courts data.
Candidatr Art. 66a StGB found in courts data.
Candidatr Art. 177 DBG found in courts data.
Candidatr Art. 34 Abs. 2 RPV found in courts data.
Candidatr Art. 9 RPG found in courts data.
Candidatr Art. 21 IPRG found in courts data.
Candidatr Art. 11a Abs. 2 DSG found in courts data.
Candidatr Art. 36 BV found in courts data.
Candidatr Art. 237 ZPO found in courts data.
Candidatr Art. 34 DSG found in courts data.
Candidatr Art. 260 StPO found in courts data.
Candidatr Art. 493 ZGB found in courts data.
Candidatr Art. 3 URG found in courts data.
Candidatr Art. 8 AsylG found in courts data.
Candidatr Art. 186 DBG found in courts data.
Candidatr Art. 24b RPG found in courts data.
Candidatr Art. 647d ZGB found in courts data.
Candidatr Art. 210 OR found in courts data.
Candidatr Art. 187 OR found in courts data.
Candidatr Art. 4a VStG found in courts data.
Candidatr Art. 975 ZGB found in courts data.
Candidatr Art. 86a ZGB found in courts data.
Candidatr Art. 527 Abs. 4 ZGB found in courts data.
Candidatr Art. 712i ZGB found in courts data.
Candidatr Art. 33 FINMAG found in courts data.
Candidatr Art. 263 StGB found in courts data.
Candidatr Art. 59 StGB found in courts data.
Candidatr Art. 38 FINMAG found in courts data.
Candidatr Art. 483 ZGB found in courts data.
Candidatr Art. 17 BV found in courts data.
Candidatr Art. 158 ZPO found in courts data.
Candidatr Art. 60 LugÜ found in courts data.
Candidatr Art. 108 SchKG found in courts data.
Candidatr Art. 90 IPRG found in courts data.
Candidatr Art. 112 OR found in courts data.
Candidatr Art. 849 ZGB found in courts data.
Candidatr Art. 105 BGG found in courts data.
Candidatr Art. 45 IPRG found in courts data.
Candidatr Art. 216 OR found in courts data.
Candidatr Art. 8 BV found in courts data.
Candidatr Art. 559 ZGB found in courts data.
Candidatr Art. 14 DSG found in courts data.
Candidatr Art. 842 ZGB found in courts data.
Candidatr Art. 260 SchKG found in courts data.
Candidatr Art. 26 HMG found in courts data.
Candidatr Art. 241 ZGB found in courts data.
Candidatr Art. 73 BPR found in courts data.
Candidatr Art. 19 BetmG found in courts data.
Candidatr Art. 474 ZGB found in courts data.
Candidatr Art. 718a OR found in courts data.
Candidatr Art. 31 FINMAG found in courts data.
Candidatr Art. 24c RPG found in courts data.
Candidatr Art. 801 ZGB found in courts data.
Candidatr Art. 85a AIG found in courts data.
Candidatr Art. 65a IRSG found in courts data.
Candidatr Art. 112 IPRG found in courts data.
Candidatr Art. 8 StGB found in courts data.
Candidatr Art. 679 ZGB found in courts data.
Candidatr Art. 279 ZGB found in courts data.
Candidatr Art. 306 StPO found in courts data.
Candidatr Art. 29 URG found in courts data.
Candidatr Art. 12 JStG found in courts data.
Candidatr Art. 260 ZPO found in courts data.
Candidatr Art. 21 AIG found in courts data.
Candidatr Art. 20 IPRG found in courts data.
Candidatr Art. 27 Abs. 4 DSG found in courts data.
Candidatr Art. 321a OR found in courts data.
Candidatr Art. 443 ZGB found in courts data.
Candidatr Art. 488 ZGB found in courts data.
Candidatr Art. 83 IPRG found in courts data.
Candidatr Art. 408 ZGB found in courts data.
Candidatr Art. 84 OR found in courts data.
Candidatr Art. 46 Abs. 1 KVV found in courts data.
Candidatr Art. 101 OR found in courts data.
Candidatr Art. 41a USG found in courts data.
Candidatr Art. 655a ZGB found in courts data.
Candidatr Art. 27 ZGB found in courts data.
Candidatr Art. 15 HMG found in courts data.
Candidatr Art. 17 SchKG found in courts data.
Candidatr Art. 1 MSchG found in courts data.
Candidatr Art. 91a SVG found in courts data.
Candidatr Art. 118 StPO found in courts data.
Candidatr Art. 12 DBG found in courts data.
Candidatr Art. 43 Abs. 1 RPV found in courts data.
Candidatr Art. 78 AIG found in courts data.
Candidatr Art. 107a AsylG found in courts data.
Candidatr Art. 58 DBG found in courts data.
Candidatr Art. 1 RPG found in courts data.
Candidatr Art. 23 LugÜ found in courts data.
Candidatr Art. 321e OR found in courts data.
Candidatr Art. 362 ZGB found in courts data.
Candidatr Art. 91 SVG found in courts data.
Candidatr Art. 50 PatG found in courts data.
Candidatr Art. 243 ZPO found in courts data.
Candidatr Art. 130 GBV found in courts data.
Candidatr Art. 26 WV found in courts data.
Candidatr Art. 969 ZGB found in courts data.
Candidatr Art. 93 BGG found in courts data.
Candidatr Art. 479 ZGB found in courts data.
Candidatr Art. 176 DBG found in courts data.
Candidatr Art. 3 MSchG found in courts data.
Candidatr Art. 12 DSG found in courts data.
Candidatr Art. 190 Abs. 2 ZPO found in courts data.
Candidatr Art. 44 OR found in courts data.
Candidatr Art. 21 BVG found in courts data.
Candidatr Art. 180 StGB found in courts data.
Candidatr Art. 46 VwVG found in courts data.
Candidatr Art. 79a StGB found in courts data.
Candidatr Art. 61 StGB found in courts data.
Candidatr Art. 336a OR found in courts data.
Candidatr Art. 77b StGB found in courts data.
Candidatr Art. 647b ZGB found in courts data.
Candidatr Art. 495 ZGB found in courts data.
Candidatr Art. 37 IRSG found in courts data.
Candidatr Art. 98 GBV found in courts data.
Candidatr Art. 5 IPRG found in courts data.
Candidatr Art. 184 StGB found in courts data.
Candidatr Art. 946 ZGB found in courts data.
Candidatr Art. 52 ZGB found in courts data.
Candidatr Art. 32 BV found in courts data.
Candidatr Art. 20 USG found in courts data.
Candidatr Art. 426 ZGB found in courts data.
Candidatr Art. 7 RAG found in courts data.
Candidatr Art. 239 StGB found in courts data.
Candidatr Art. 116 OR found in courts data.
Candidatr Art. 18 OR found in courts data.
Candidatr Art. 144 StGB found in courts data.
Candidatr Art. 205 OR found in courts data.
Candidatr Art. 42 OR found in courts data.
Candidatr Art. 27 DSG found in courts data.
Candidatr Art. 757 OR found in courts data.
Candidatr Art. 33 OR found in courts data.
Candidatr Art. 22 BV found in courts data.
Candidatr Art. 113 StPO found in courts data.
Candidatr Art. 8 AVIG found in courts data.
Candidatr Art. 4 Abs. 4 DSG found in courts data.
Candidatr Art. 140 StGB found in courts data.
Candidatr Art. 469 ZGB found in courts data.
Candidatr Art. 66 FINIG found in courts data.
Candidatr Art. 3 ZGB found in courts data.
Candidatr Art. 6 ZPO found in courts data.
Candidatr Art. 655 ZGB found in courts data.
Candidatr Art. 32 VGG found in courts data.
Candidatr Art. 25 USG found in courts data.
Candidatr Art. 4 StromVV found in courts data.
Candidatr Art. 680 OR found in courts data.
Candidatr Art. 48a StGB found in courts data.
Candidatr Art. 960e OR found in courts data.
Candidatr Art. 16 EleG found in courts data.
Candidatr Art. 28 URG found in courts data.
Candidatr Art. 34 ZPO found in courts data.
Candidatr Art. 177 IPRG found in courts data.
Candidatr Art. 361 OR found in courts data.
Candidatr Art. 967 OR found in courts data.
Candidatr Art. 3 AsylG found in courts data.
Candidatr Art. 299 StPO found in courts data.
Candidatr Art. 111 BGG found in courts data.
Candidatr Art. 27 FinfraG found in courts data.
Candidatr Art. 15 StromVG found in courts data.
Candidatr Art. 3 BEG found in courts data.
Candidatr Art. 23 ZGB found in courts data.
Candidatr Art. 206 ZGB found in courts data.
Candidatr Art. 24 UVG found in courts data.
Candidatr Art. 12 BüG found in courts data.
Candidatr Art. 102 StGB found in courts data.
Candidatr Art. 494 ZGB found in courts data.
Candidatr Art. 26 BankG found in courts data.
Candidatr Art. 215 ZGB found in courts data.
Candidatr Art. 423 OR found in courts data.
Candidatr Art. 959 ZGB found in courts data.
Candidatr Art. 27 Abs. 5 DSG found in courts data.
Candidatr Art. 317 StGB found in courts data.
Candidatr Art. 182 ZGB found in courts data.
Candidatr Art. 11 PrHG found in courts data.
Candidatr Art. 71 VwVG found in courts data.
Candidatr Art. 26a VStV found in courts data.
Candidatr Art. 100 BGG found in courts data.
Candidatr Art. 58 SVG found in courts data.
Candidatr Art. 29 OR found in courts data.
Candidatr Art. 398 OR found in courts data.
Candidatr Art. 127 BV found in courts data.
Candidatr Art. 125 ZGB found in courts data.
Candidatr Art. 9 Abs. 5 DSG found in courts data.
Candidatr Art. 357 OR found in courts data.
Candidatr Art. 282 StPO found in courts data.
Candidatr Art. 9 IPRG found in courts data.
Candidatr Art. 32 JStPO found in courts data.
Candidatr Art. 949a ZGB found in courts data.
Candidatr Art. 86 BGG found in courts data.
Candidatr Art. 51 ATSG found in courts data.
Candidatr Art. 357b OR found in courts data.
Candidatr Art. 10a USG found in courts data.
Candidatr Art. 34 FINMAG found in courts data.
Candidatr Art. 3 RPG found in courts data.
Candidatr Art. 116 IPRG found in courts data.
Candidatr Art. 294 StGB found in courts data.
Candidatr Art. 72 StGB found in courts data.
Candidatr Art. 712g ZGB found in courts data.
Candidatr Art. 956a ZGB found in courts data.
Candidatr Art. 63 AIG found in courts data.
Candidatr Art. 336 OR found in courts data.
Candidatr Art. 83 AsylG found in courts data.
Candidatr Art. 1 OR found in courts data.
Candidatr Art. 18a EBG found in courts data.
Candidatr Art. 20 OR found in courts data.
Candidatr Art. 236 ZPO found in courts data.
Candidatr Art. 308 ZPO found in courts data.
Candidatr Art. 17 DSG found in courts data.
Candidatr Art. 212 ZPO found in courts data.
Candidatr Art. 725 OR found in courts data.
Candidatr Art. 972 ZGB found in courts data.
Candidatr Art. 1 Abs. 2 LugÜ found in courts data.
Candidatr Art. 647a ZGB found in courts data.
Candidatr Art. 340a OR found in courts data.
Candidatr Art. 271 SchKG found in courts data.
Candidatr Art. 965 ZGB found in courts data.
Candidatr Art. 258 ZPO found in courts data.

KeyboardInterrupt:

In [28]:
def get_base_article(citation):
    base = re.sub(r'\sAbs\.\s\d+', '', citation)
    base = re.sub(r'\sZiff\.\s\d+', '', base)
    return base.strip()

In [29]:
from collections import defaultdict
parent_to_children = defaultdict(list)

for cit in articles_in_laws:
    parent = get_base_article(cit)
    parent_to_children[parent].append(cit)

In [34]:
true_for_cleaning = set()

for candidate_to_delete in in_training_not_in_laws_not_in_courts:
    candidate_parent = get_base_article(candidate_to_delete)
    if candidate_parent not in parent_to_children:
        true_for_cleaning.add(candidate_to_delete)

print(f"Total candidates in training data not in laws or courts: {len(in_training_not_in_laws_not_in_courts)}")
print(f"Total articles for cleaning: {len(true_for_cleaning)}")

Total candidates in training data not in laws or courts: 767
Total articles for cleaning: 53

In [35]:
valid_ids = set(articles_in_laws).union(set(articles_in_courts))
valid_ids = valid_ids.union(set(parent_to_children.keys()))

def clean_gold_labels(label_string):
    labels = [l.strip() for l in label_string.split(';')]
    
    valid_labels = [l for l in labels if l in valid_ids]

    return ";".join(valid_labels)


# use a copy just in care we need the original later, but we want to add a new column with cleaned gold labels

copy_train_data = train_data.copy()
copy_train_data['cleaned_gold'] = copy_train_data['gold_citations'].apply(clean_gold_labels)

copy_train_data = copy_train_data[copy_train_data['cleaned_gold'] != ""].copy()
copy_train_data.head(5)

,query_id,query,gold_citations,query_len,num_citations,cleaned_gold
0,train_0001,Die A AG betreibt seit den 1970er-Jahren auf d...,Art. 10a Abs. 1 USG;Art. 2 Abs. 1 UVPV;Art. 10...,1495,3,Art. 10a Abs. 1 USG;Art. 2 Abs. 1 UVPV
1,train_0002,Die Alpha Consulting AG kann nun ihr Grundstüc...,Art. 975 ZGB;Art. 974 Abs. 2 ZGB;Art. 973 ZGB;...,1376,11,Art. 975 ZGB;Art. 974 Abs. 2 ZGB;Art. 973 ZGB;...
2,train_0003,Das Kompetenzzentrum Völkerstrafrecht bei der ...,Art. 264m StGB,1095,1,Art. 264m StGB
3,train_0004,Die Linzer Stadtbahn AG ('LiSA') ist die priva...,Art. 176 Abs. 1 IPRG;Art. 186 Abs. 1 IPRG;Art....,2899,4,Art. 176 Abs. 1 IPRG;Art. 186 Abs. 1 IPRG;Art....
4,train_0005,Die Stadt Winterthur beschloss am 10. Februar ...,Art. 93 Abs. 1 BGG;Art. 89 Abs. 1 BGG;Art. 89 ...,5763,6,Art. 93 Abs. 1 BGG;Art. 89 Abs. 1 BGG;Art. 89 ...

In [36]:
copy_train_data.describe()

          query_len  num_citations
count   1125.000000    1125.000000
mean    1622.479111       4.116444
std     3032.639461       4.525899
min       40.000000       1.000000
25%      442.000000       1.000000
50%     1016.000000       3.000000
75%     1794.000000       5.000000
max    32767.000000      44.000000

In [37]:
copy_train_data.to_csv(DATA_PATH / "processed" / "cleaned_train.csv", index=False)